import fs from 'node:fs/promises';
import {Workbook,SpreadsheetFile} from '@oai/artifact-tool';
const root=process.env.QUINCY_FINANCE_DIR || process.cwd(), out=root;
await fs.mkdir(out,{recursive:true});
const money='$'+'#,##0;($#,##0);"-"', num='#,##0;(#,##0);"-"';
const captures={}, evidence=[], caseNames=new Map();
const col=n=>String.fromCharCode(64+n);
function sheet(w,name,title,cols=12){let s=w.worksheets.add(name);s.showGridLines=false;s.getRange(`A1:${col(cols)}65`).format.font={name:'Arial',size:11,color:'#172c43'};s.getRange('A1:B65').format.columnWidth=3;s.getRange(`C1:C65`).format.columnWidth=42;s.getRange(`D1:${col(cols)}65`).format.columnWidth=17;s.getRange(`C1:${col(cols)}65`).format.rowHeight=22;s.getRange('C2').values=[[title]];s.getRange('C2').format.font={size:16,bold:true,color:'#17324d'};s.getRange(`C3:${col(cols)}3`).format.borders={bottom:{style:'thin',color:'#9bafc4'}};return s;}
function v(s,a,val){s.getRange(a).values=[[val]];if(typeof val==='number')s.getRange(a).format.font.color='#0759e6';}
function f(s,a,formula){s.getRange(a).formulas=[[formula]];s.getRange(a).format.font.color=formula.includes('!')?'#087a55':'#111111';}
function table(s,range,rows){s.getRange(range).values=rows;s.getRange(range).format.wrapText=true;s.getRange(range).format.autofitRows();let h=s.getRange(range).getRow(0);h.format.fill='#17324d';h.format.font={bold:true,color:'#ffffff'};h.format.horizontalAlignment='center';}
function caseControl(a,names=['Base','Downside','Upside']){caseNames.set(a,names);v(a,'C5','Case selected');v(a,'D5',1);a.getRange('D5').dataValidation={rule:{type:'list',values:['1','2','3']}};v(a,'F5',names.map((x,i)=>(i+1)+' '+x).join(' / '));a.getRange('F5:K6').merge();a.getRange('F5:K6').format.wrapText=true;f(a,'D4',`=CHOOSE(D5,${names.map(x=>'"'+x+'"').join(',')})`);}
function selected(s){v(s,'C4','Case selected');f(s,'D4',"='Assumptions'!D4");s.getRange('D4:F4').merge();}
function driver(a,row,name,base,down,up,fmt='0.0%'){v(a,`C${row}`,name+' (active)');f(a,`D${row}`,`=IF(ISNUMBER(CHOOSE($D$5,D${row+1},D${row+2},D${row+3})),CHOOSE($D$5,D${row+1},D${row+2},D${row+3}),NA())`);for(let i=0;i<3;i++){v(a,`C${row+i+1}`,caseNames.get(a)[i]);v(a,`D${row+i+1}`,[base,down,up][i]);}a.getRange(`D${row}:D${row+3}`).setNumberFormat(fmt);a.getRange(`C${row}:D${row}`).format.fill='#eaf1f8';}
function chart(s,range,title,type='line',from='H8',to='O23'){let c=s.charts.add(type,s.getRange(range));c.title=title;c.titleTextStyle.typeface='Arial';c.titleTextStyle.fontSize=14;c.hasLegend=true;c.xAxis={axisType:'textAxis',textStyle:{typeface:'Arial',fontSize:11}};c.yAxis={numberFormatCode:'$0.0,,"M"',numberFormatSourceLinked:false,textStyle:{typeface:'Arial',fontSize:11}};c.setPosition(from,to);c.series.items.forEach((x,i)=>{x.fill=['#17324d','#15a6ac','#a95f18'][i%3];x.line={fill:['#17324d','#15a6ac','#a95f18'][i%3],style:'solid',width:2};});return c;}
function actions(w,rows){let s=sheet(w,'Actions','Decision ownership and approval');table(s,'C6:I'+(6+rows.length),[['Action','Proposed owner','Due from approval','Trigger / evidence','Approval needed','Status','Evidence link'],...rows.map(r=>[...r,'Proposed',''])]);s.getRange('C6:I'+(6+rows.length)).format.columnWidth=27;s.getRange('H7:H'+(6+rows.length)).dataValidation={rule:{type:'list',values:['Proposed','In progress','Completed','Blocked']}};v(s,'C4','Roles and deadlines are proposed within a synthetic case.');s.getRange('C4:I4').merge();s.freezePanes.freezeRows(6);return s;}
function terminal(w,rows){let s=sheet(w,'Audit','Reconciliation checks');table(s,'C6:E'+(6+rows.length),[['Check','Difference','Tolerance (USD)'],...rows.map(r=>[r[0],null,r[2]??0.01])]);rows.forEach((r,i)=>f(s,'D'+(7+i),r[1]));s.getRange('D7:E'+(6+rows.length)).setNumberFormat('0.00');s.getRange('D7:D'+(6+rows.length)).conditionalFormats.addCustom('ABS(D7)>E7',{fill:'#fee2e2',font:{bold:true,color:'#b91c1c'}});return s;}
async function finish(w,slug,metricCells,extraCheck){w.recalculate();let ass=w.worksheets.getItem('Assumptions');captures[slug]=[];for(let c=1;c<=3;c++){v(ass,'D5',c);w.recalculate();let vals={case:c,name:ass.getRange('D4').values[0][0]};for(const [k,[s,a]] of Object.entries(metricCells))vals[k]=w.worksheets.getItem(s).getRange(a).values[0][0];captures[slug].push(vals);}
v(ass,'D5',1);w.recalculate();if(extraCheck)await extraCheck(w);w.recalculate();let errors=await w.inspect({kind:'match',searchTerm:'#REF!|#DIV/0!|#VALUE!|#NAME\\?|#NUM!|#NULL!|#SPILL!|#CALC!|#N/A',options:{useRegex:true,maxResults:20},maxChars:3000});evidence.push({slug,errors:errors.ndjson,cases:captures[slug]});console.log(slug,JSON.stringify(captures[slug]),errors.ndjson);
for(const s of w.worksheets.items){if(s.name==='Summary'){s.getRange('D7:F15').format.font.color='#172c43';s.getRange('D17:F29').format.font.color='#172c43';}  const range=s.name==='Summary'?'C1:O29':s.name==='Actions'?'C1:I12':s.name==='Detail'?'C1:N42':s.name==='Invoices'?'C1:L36':s.name==='Assumptions'?'C1:K40':s.name==='Cash Flows'?'C1:L42':s.name==='Weekly'?'C1:P26':s.name==='Monthly'?'C1:O28':'C1:L28';let b=await w.render({sheetName:s.name,range,scale:1.5,format:'png'});await fs.writeFile(out+'/'+slug+'-'+s.name.replaceAll(' ','_')+'.png',new Uint8Array(await b.arrayBuffer()));}
let file=await SpreadsheetFile.exportXlsx(w);await file.save(out+'/'+slug+'.xlsx');}

// Operating plan: preserve the earlier portfolio case's 18 H1 synthetic records.
{
const w=Workbook.create();let sum=sheet(w,'Summary','Transportation operating plan (2026)',15),a=sheet(w,'Assumptions','Operating assumptions'),d=sheet(w,'Detail','Segment operating build',14),m=sheet(w,'Monthly','Monthly profit and cash forecast',15),b=sheet(w,'Variance','July EBITDA variance to reference plan'),src=sheet(w,'Source','Synthetic H1 source records',10);caseControl(a);[sum,d,m,b].forEach(selected);
driver(a,8,'Monthly unit growth',.012,-.012,.027);driver(a,13,'Monthly price growth',.018,0,.025);driver(a,18,'Monthly unit cost inflation',.025,.035,.020);driver(a,23,'Monthly operating expense growth',.020,.025,.018);
table(a,'F8:I15',[['Cash driver','Value','Units','Basis'],['Opening July cash',500000,'USD','Synthetic assumption'],['Receivable days',35,'days','30-day month approximation'],['Payable days',20,'days','Variable costs only'],['Monthly depreciation',20000,'USD','Existing asset base simplified'],['Monthly cash capex',25000,'USD','Maintenance capex assumption'],['Cash tax rate',.25,'fraction','Tax only on positive EBIT'],['Minimum cash',250000,'USD','Illustrative management threshold']]);a.getRange('G9:G15').format.font.color='#0759e6';a.getRange('F8:I15').format.columnWidth=23;v(a,'C31','Monthly rates compound. No financing, dividends, or loss carryforwards.');a.getRange('C31:K32').merge();a.getRange('C31:K32').format.wrapText=true;
let csv=await fs.readFile(root+'/source/synthetic_actuals_h1.csv','utf8');let lines=csv.trim().split(/\r?\n/).slice(1).map(x=>x.split(','));let raw=lines.map(x=>[new Date(x[0]+'-01T00:00:00Z'),x[1],...x.slice(2).map(Number)]);table(src,'C6:I24',[['Month','Segment','Units','Price / unit','Variable cost / unit','Fixed cost','Opex'],...raw]);src.getRange('C7:C24').setNumberFormat('mmm-yy');src.getRange('E7:I24').setNumberFormat(num);src.getRange('F7:G24').setNumberFormat('0.00');v(src,'C27','Source: existing fpa-forecast-scenario-planning synthetic_actuals_h1.csv.');src.getRange('C27:K28').merge();src.getRange('C27:K28').format.wrapText=true;
table(d,'C6:N6',[['Month','Segment','Units','Price / unit','Variable cost / unit','Fixed','Opex','Revenue','Variable cost','EBITDA','Seasonality','Original fixed']]);d.getRange('C7:C42').setNumberFormat('mmm-yy');d.getRange('E7:N42').setNumberFormat(money);d.getRange('E7:E42').setNumberFormat(num);d.getRange('F7:G42').setNumberFormat('0.00');let seasonal=[.94,.92,1,.98,1.02,1,1.01,1.04,1.01,1.08,1.13,1.17],orig=[89000,76000,42000];
for(let i=0;i<36;i++){let r=7+i,mo=Math.floor(i/3)+1,j=i%3;v(d,'C'+r,new Date(Date.UTC(2026,mo-1,1)));v(d,'D'+r,['Core','Enterprise','Services'][j]);v(d,'M'+r,seasonal[mo-1]);v(d,'N'+r,orig[j]);if(i<18){for(let c=5;c<=9;c++)f(d,col(c)+r,`='Source'!${col(c)}${r}`);}else{let june=22+j,k=mo-6;f(d,'E'+r,`=ROUND(E${june}*(1+'Assumptions'!$D$8)^${k}*M${r}/M${june},0)`);f(d,'F'+r,`=F${june}*(1+'Assumptions'!$D$13)^${k}`);f(d,'G'+r,`=G${june}*(1+'Assumptions'!$D$18)^${k}`);f(d,'H'+r,`=N${r}*(1+0.001*${mo})*(1+'Assumptions'!$D$18*0.35)^${k}`);let originalOpex=[61000,82000,51000][j];f(d,'I'+r,`='Source'!I${june}/(1+0.002*6)*(1+0.002*${mo})*(1+'Assumptions'!$D$23)^${k}`);}f(d,'J'+r,`=E${r}*F${r}`);f(d,'K'+r,`=E${r}*G${r}`);f(d,'L'+r,`=J${r}-SUM(K${r},H${r}:I${r})`);}
let ml=['Revenue','Variable cost','Fixed cost','Opex','EBITDA','EBITDA margin','Depreciation','EBIT','Cash taxes','Receivables','Payables','Change in net working capital','Cash capex','Operating cash after capex','Opening cash','Ending cash'];ml.forEach((x,i)=>v(m,'C'+(7+i),x));for(let k=0;k<12;k++){let c=col(4+k);v(m,c+'6',new Date(Date.UTC(2026,k,1)));m.getRange(c+'6').setNumberFormat('mmm-yy');[7,8,9,10,11].forEach((r,j)=>f(m,c+r,`=SUMIFS('Detail'!$${['J','K','H','I','L'][j]}$7:$${['J','K','H','I','L'][j]}$42,'Detail'!$C$7:$C$42,${c}$6)`));f(m,c+'12',`=${c}11/${c}7`);if(k>=6){f(m,c+'13',"='Assumptions'!$G$12");f(m,c+'14',`=${c}11-${c}13`);f(m,c+'15',`=MAX(0,${c}14)*'Assumptions'!$G$14`);f(m,c+'16',`=${c}7*'Assumptions'!$G$10/30`);f(m,c+'17',`=${c}8*'Assumptions'!$G$11/30`);let prev=col(3+k);f(m,c+'18',k===6?`=(${c}16-${c}17)-(${prev}7*'Assumptions'!$G$10/30-${prev}8*'Assumptions'!$G$11/30)`:`=(${c}16-${c}17)-(${prev}16-${prev}17)`);f(m,c+'19',"='Assumptions'!$G$13");f(m,c+'20',`=${c}14-${c}15+${c}13-${c}18-${c}19`);f(m,c+'21',k===6?"='Assumptions'!$G$9":`=${prev}22`);f(m,c+'22',`=SUM(${c}20:${c}21)`);}}
m.getRange('D7:O22').setNumberFormat(money);m.getRange('D12:O12').setNumberFormat('0.0%');m.freezePanes.freezeRows(6);m.freezePanes.freezeColumns(3);v(m,'C25','Jan-Jun: synthetic history. Cash schedule covers Jul-Dec only.');m.getRange('C25:K25').merge();
table(b,'C6:L9',[['Segment','Plan units','Plan price','Plan unit cost','Volume','Price','Unit cost','Fixed / opex','Total variance','Active EBITDA'],...['Core','Enterprise','Services'].map(x=>[x,null,null,null,null,null,null,null,null,null])]);for(let j=0;j<3;j++){let r=7+j,june=22+j,july=25+j;f(b,'D'+r,`=ROUND('Detail'!E${june}*1.01,0)`);f(b,'E'+r,`='Detail'!F${june}`);f(b,'F'+r,`='Detail'!G${june}`);f(b,'G'+r,`=('Detail'!E${july}-D${r})*(E${r}-F${r})`);f(b,'H'+r,`='Detail'!E${july}*('Detail'!F${july}-E${r})`);f(b,'I'+r,`=-'Detail'!E${july}*('Detail'!G${july}-F${r})`);f(b,'J'+r,`=-('Detail'!H${july}+'Detail'!I${july}-'Detail'!H${june}-'Detail'!I${june})`);f(b,'K'+r,`=SUM(G${r}:J${r})`);f(b,'L'+r,`='Detail'!L${july}`);}v(b,'C12','Reference July EBITDA');f(b,'D12',"=SUMPRODUCT(D7:D9,E7:E9)-SUMPRODUCT(D7:D9,F7:F9)-SUM('Detail'!H22:I24)");v(b,'C13','Active July EBITDA');f(b,'D13',"='Monthly'!J11");v(b,'C14','Total driver variance');f(b,'D14','=SUM(K7:K9)');b.getRange('G7:L9').setNumberFormat(money);b.getRange('D12:D14').setNumberFormat(money);v(b,'C17','Reference plan: June unit economics, July seasonality, June fixed/opex.');b.getRange('C17:L18').merge();b.getRange('C17:L18').format.wrapText=true;
table(sum,'C6:E11',[['Metric','Value','Period / basis'],['Revenue',null,'Full year'],['EBITDA',null,'Full year'],['EBITDA margin',null,'Full year'],['Ending cash',null,'December'],['Lowest cash',null,'Jul-Dec']]);f(sum,'D7',"=SUM('Monthly'!D7:O7)");f(sum,'D8',"=SUM('Monthly'!D11:O11)");f(sum,'D9','=D8/D7');f(sum,'D10',"='Monthly'!O22");f(sum,'D11',"=MIN('Monthly'!J22:O22)");sum.getRange('D7:D11').setNumberFormat(money);sum.getRange('D9').setNumberFormat('0.0%');sum.getRange('E6:E11').format.columnWidth=22;
table(sum,'C16:E28',[['Month','Revenue','EBITDA'],...Array.from({length:12},(_,i)=>[new Date(Date.UTC(2026,i,1)).toLocaleString('en-US',{month:'short',timeZone:'UTC'}),null,null])]);for(let i=0;i<12;i++){f(sum,'D'+(17+i),`='Monthly'!${col(4+i)}7`);f(sum,'E'+(17+i),`='Monthly'!${col(4+i)}11`);}sum.getRange('D17:E28').setNumberFormat(money);chart(sum,'C16:E28','Monthly revenue and EBITDA (USD)');v(sum,'H25','Review price realization, volume, and cost inflation together.');sum.getRange('H25:O26').merge();sum.getRange('H25:O26').format.wrapText=true;v(sum,'H27','Synthetic case. Cash forecast excludes debt and financing.');sum.getRange('H27:O28').merge();sum.getRange('H27:O28').format.wrapText=true;
let review=sheet(w,'Review','Simulated operating follow-up');table(review,'C6:H10',[['Measure','Frozen plan','Simulated observation','Variance','Review threshold','Decision'],['July revenue',null,872000,null,.05,null],['July EBITDA',null,-48000,null,0,null],['July ending cash',null,401000,null,250000,null],['On-time service',.95,.932,null,.95,null]]);v(review,'D7',936000);v(review,'D8',-28000);v(review,'D9',420000);for(let r=7;r<=10;r++)f(review,'F'+r,`=E${r}-D${r}`);f(review,'H7','=IF(E7<D7*(1-G7),"Reforecast","Monitor")');f(review,'H8','=IF(E8<G8,"Review margin drivers","Monitor")');f(review,'H9','=IF(E9<G9,"Escalate cash","Monitor")');f(review,'H10','=IF(E10<G10,"Review service capacity","Monitor")');review.getRange('D7:F9').setNumberFormat(money);review.getRange('D10:G10').setNumberFormat('0.0%');review.getRange('C6:H10').format.columnWidth=26;v(review,'C13','Separate synthetic monitoring exercise. Frozen plan is an illustrative management target.');review.getRange('C13:L14').merge();review.getRange('C13:L14').format.wrapText=true;
actions(w,[['Validate price and cost assumptions','Finance + Sales','Day 5','July driver variance reconciled','Finance lead'],['Review low-margin contracts','Commercial + Operations','Day 10','EBITDA margin below 3%','Commercial lead'],['Reforecast and approve actions','Finance lead','Monthly close + 5 days','Volume misses plan >5%','Business unit lead'],['Monitor cash and capex','Treasury + Operations','Weekly','Cash below $250,000','Finance lead']]);terminal(w,[['July bridge',"='Variance'!D13-'Variance'!D12-'Variance'!D14"],['Cash roll-forward',"='Monthly'!O22-'Assumptions'!G9-SUM('Monthly'!J20:O20)"],['H1 revenue to raw inputs',"=SUM('Monthly'!D7:I7)-SUMPRODUCT('Source'!E7:E24,'Source'!F7:F24)"]]);
await finish(w,'Operating_Plan',{revenue:['Summary','D7'],ebitda:['Summary','D8'],margin:['Summary','D9'],endingCash:['Summary','D10'],minCash:['Summary','D11'],julyBridge:['Audit','D7']});}

// Fleet appraisal: three mutually exclusive operating alternatives.
{
const w=Workbook.create();let s=sheet(w,'Summary','Fleet investment committee',15),a=sheet(w,'Assumptions','Fleet assumptions'),b=sheet(w,'Cash Flows','Five-year fleet cash flows');caseControl(a,['Base','Fuel shock','Low utilization']);[s,b].forEach(selected);
driver(a,8,'Discount rate',.08,.10,.08);driver(a,13,'Fuel price per gallon',4,5,4,'$0.00');driver(a,18,'Annual miles per vehicle',70000,70000,45000,num);driver(a,23,'Old annual maintenance / vehicle',22000,26000,22000,money);
table(a,'F8:H25',[['Input','Value','Units'],['Fleet size',6,'vehicles'],['Purchase cost / vehicle',130000,'USD'],['Sale of old / vehicle now',20000,'USD'],['Old terminal resale / vehicle',7000,'USD'],['New terminal resale / vehicle',42000,'USD'],['Old fuel economy',6,'mpg'],['New fuel economy',7.2,'mpg'],['New maintenance / vehicle',9000,'USD / year'],['Old downtime / vehicle',12,'days / year'],['New downtime / vehicle',4,'days / year'],['Downtime cash cost',1800,'USD / day'],['Lease / vehicle / year',33000,'USD'],['Lease upfront deposit',50000,'USD'],['Upfront capital limit',700000,'USD'],['Annual cost inflation',.03,'fraction'],['Discount years',5,'years'],['Lease deposit returned at end',50000,'USD']]);a.getRange('F8:H25').format.columnWidth=28;a.getRange('G9:G25').format.font.color='#0759e6';v(a,'C38','Synthetic USD assumptions. Pre-tax appraisal; identical service output.');a.getRange('C38:K39').merge();a.getRange('C38:K39').format.wrapText=true;
let labels={7:'Keep: maintenance',8:'Keep: fuel',9:'Keep: downtime',10:'Keep: total outflow',11:'Keep: residual receipt',12:'Keep: net cash flow',15:'Replace: maintenance',16:'Replace: fuel',17:'Replace: downtime',18:'Replace: total outflow',19:'Replace: residual receipt',20:'Replace: net cash flow',23:'Lease: rental',24:'Lease: fuel',25:'Lease: downtime',26:'Lease: total outflow',27:'Lease: returned deposit',28:'Lease: net cash flow',31:'Replace less keep: incremental CF',32:'Lease less keep: incremental CF',34:'Discount factor',35:'Keep: present value',36:'Replace: present value',37:'Lease: present value'};for(const [r,l]of Object.entries(labels))v(b,'C'+r,l);
for(let yr=0;yr<=5;yr++){let c=col(4+yr);v(b,c+'6',yr);if(!yr){[12,31,32].forEach(r=>f(b,c+r,r===12?'=0':r===31?`=${c}20-${c}12`:`=${c}28-${c}12`));f(b,c+'20',"=-'Assumptions'!G9*('Assumptions'!G10-'Assumptions'!G11)");f(b,c+'28',"='Assumptions'!G9*'Assumptions'!G11-'Assumptions'!G21");}else{
f(b,c+'7',`='Assumptions'!$G$9*'Assumptions'!$D$23*(1+'Assumptions'!$G$23)^(${c}$6-1)`);f(b,c+'8',`='Assumptions'!$G$9*'Assumptions'!$D$18/'Assumptions'!$G$14*'Assumptions'!$D$13*(1+'Assumptions'!$G$23)^(${c}$6-1)`);f(b,c+'9',`='Assumptions'!$G$9*'Assumptions'!$G$17*'Assumptions'!$G$19*(1+'Assumptions'!$G$23)^(${c}$6-1)`);f(b,c+'10',`=SUM(${c}7:${c}9)`);f(b,c+'11',yr===5?"='Assumptions'!G9*'Assumptions'!G12":'=0');f(b,c+'12',`=-${c}10+${c}11`);
f(b,c+'15',`='Assumptions'!$G$9*'Assumptions'!$G$16*(1+'Assumptions'!$G$23)^(${c}$6-1)`);f(b,c+'16',`='Assumptions'!$G$9*'Assumptions'!$D$18/'Assumptions'!$G$15*'Assumptions'!$D$13*(1+'Assumptions'!$G$23)^(${c}$6-1)`);f(b,c+'17',`='Assumptions'!$G$9*'Assumptions'!$G$18*'Assumptions'!$G$19*(1+'Assumptions'!$G$23)^(${c}$6-1)`);f(b,c+'18',`=SUM(${c}15:${c}17)`);f(b,c+'19',yr===5?"='Assumptions'!G9*'Assumptions'!G13":'=0');f(b,c+'20',`=-${c}18+${c}19`);
f(b,c+'23',`='Assumptions'!$G$9*'Assumptions'!$G$20*(1+'Assumptions'!$G$23)^(${c}$6-1)`);f(b,c+'24',`=${c}16`);f(b,c+'25',`=${c}17`);f(b,c+'26',`=SUM(${c}23:${c}25)`);f(b,c+'27',yr===5?"='Assumptions'!G25":'=0');f(b,c+'28',`=-${c}26+${c}27`);f(b,c+'31',`=${c}20-${c}12`);f(b,c+'32',`=${c}28-${c}12`);}
f(b,c+'34',`=1/(1+'Assumptions'!$D$8)^${c}$6`);for(const [r,cf]of [[35,12],[36,20],[37,28]])f(b,c+r,`=${c}${cf}*${c}34`);}
b.getRange('D7:I37').setNumberFormat(money);b.getRange('D34:I34').setNumberFormat('0.000');v(b,'C40','Year 0 sale proceeds apply only when old fleet is disposed.');b.getRange('C40:K41').merge();b.getRange('C40:K41').format.wrapText=true;
table(s,'C6:G9',[['Alternative','PV net costs','Upfront cash needed','NPV gain vs keep','Budget eligible'],['Keep',null,null,null,null],['Replace',null,null,null,null],['Lease',null,null,null,null]]);for(let i=0;i<3;i++){let r=7+i;f(s,'D'+r,`=-SUM('Cash Flows'!D${35+i}:I${35+i})`);f(s,'E'+r,`=MAX(0,-'Cash Flows'!D${[12,20,28][i]})`);f(s,'F'+r,i===0?'=0':`=$D$7-D${r}`);f(s,'G'+r,`=IF(E${r}<='Assumptions'!$G$22,"Yes","No")`);}s.getRange('D7:F9').setNumberFormat(money);s.getRange('C6:G9').format.columnWidth=24;
v(s,'C12','Lowest modeled PV cost');f(s,'D12','=INDEX(C7:C9,MATCH(MIN(D7:D9),D7:D9,0))');v(s,'C13','Recommended alternative within budget');f(s,'D13','=IF(AND(G8="Yes",D8<=D7,OR(G9="No",D8<=D9)),"Replace",IF(AND(G9="Yes",D9<D7),"Lease","Keep"))');v(s,'C15','Approval conditions');v(s,'C16','Validate quotes, residual values, availability and tax treatment.');s.getRange('C16:G18').merge();s.getRange('C16:G18').format.wrapText=true;chart(s,'C6:D9','Five-year present value of net costs (USD)','bar','I8','O23');v(s,'C22','Lease assumes maintenance included; downtime and fuel remain.');s.getRange('C22:G24').merge();s.getRange('C22:G24').format.wrapText=true;v(s,'C26','Pre-tax comparison. Depreciation and financing are excluded.');s.getRange('C26:O27').merge();
// Native two-variable sensitivity, using the actual model inputs on Assumptions.
v(a,'F29','Replacement incremental NPV sensitivity');v(a,'G30','Discount rate across / maintenance below');a.getRange('G30:K30').merge();f(a,'G32',"='Summary'!F8");a.getRange('H32:J32').values=[[.06,.08,.10]];a.getRange('G33:G35').values=[[18000],[22000],[26000]];a.dataTables.add('G32:J35',{rowInput:'D8',columnInput:'D23'});a.getRange('H32:J32').setNumberFormat('0.0%');a.getRange('G33:J35').setNumberFormat(money);a.getRange('G32').setNumberFormat(money);a.getRange('G10:G13').setNumberFormat(money);a.getRange('G16').setNumberFormat(money);a.getRange('G19:G22').setNumberFormat(money);a.getRange('G23').setNumberFormat('0.0%');a.getRange('G25').setNumberFormat(money);
let review=sheet(w,'Review','Simulated fleet benefits review');table(review,'C6:H10',[['Measure','Plan','Simulated observation','Variance','Units','Review action'],['Annual maintenance',54000,58000,null,'USD','Review warranty and repair mix'],['Fuel economy',7.2,6.9,null,'mpg','Review duty cycle and driver factors'],['Annual fleet downtime',24,30,null,'days','Investigate service availability'],['Net upfront cash',660000,672000,null,'USD','Reconcile purchase and disposal invoices']]);for(let r=7;r<=10;r++)f(review,'F'+r,`=E${r}-D${r}`);review.getRange('C6:H10').format.columnWidth=26;review.getRange('D7:F7').setNumberFormat(money);review.getRange('D8:F8').setNumberFormat('0.0');review.getRange('D10:F10').setNumberFormat(money);v(review,'C13','Simulated review only. Annualized observations are not realized employer savings.');review.getRange('C13:L14').merge();review.getRange('C13:L14').format.wrapText=true;
actions(w,[['Obtain purchase and lease quotes','Fleet + Procurement','Day 10','Comparable service and coverage','Procurement lead'],['Approve capital and liquidity','Finance + Treasury','Day 15','Net upfront cash within $700k','Investment committee'],['Verify tax and residual assumptions','Finance','Before commitment','Tax-adjusted economics reviewed','Finance lead'],['Review benefits after commissioning','Fleet + Finance','Days 30 / 90 / 180','Maintenance, mpg, downtime vs plan','Operations lead']]);terminal(w,[['Replace incremental NPV',"='Summary'!F8-SUMPRODUCT('Cash Flows'!D31:I31,'Cash Flows'!D34:I34)"],['Lease incremental NPV',"='Summary'!F9-SUMPRODUCT('Cash Flows'!D32:I32,'Cash Flows'!D34:I34)"],['Year 0 net cash',"='Cash Flows'!D20+'Assumptions'!G9*('Assumptions'!G10-'Assumptions'!G11)"]]);await finish(w,'Fleet_Investment',{keepPV:['Summary','D7'],replacePV:['Summary','D8'],leasePV:['Summary','D9'],replaceNPV:['Summary','F8'],upfront:['Summary','E8'],recommendation:['Summary','D13']});}

// Liquidity: invoice-level timing, boundary carry-forward and explicit financing gaps.
{
const w=Workbook.create();let s=sheet(w,'Summary','13-week liquidity and working capital',15),a=sheet(w,'Assumptions','Cash timing assumptions'),b=sheet(w,'Weekly','Weekly cash forecast',16),iv=sheet(w,'Invoices','Synthetic open receivables',10),r=sheet(w,'Review','Simulated four-week forecast review');caseControl(a,['Base','Delayed receipts','Mitigation']);[s,b,iv,r].forEach(selected);driver(a,8,'Receipt delay (weeks)',0,2,2,'0');driver(a,13,'Eligible acceleration (weeks)',0,0,2,'0');driver(a,18,'Capex week',6,6,14,'0');
table(a,'F8:H16',[['Input','Value','Basis'],['Opening cash',180000,'Synthetic opening bank balance'],['Minimum cash',100000,'Management floor'],['Weekly direct cash sales',20000,'Excludes open invoice receipts'],['Weekly payroll',45000,'Cash payments'],['Weekly fuel',20000,'Cash payments'],['Weekly supplier AP',35000,'Cash payments'],['Weekly lease payments',12000,'Cash payments'],['One-time capex',90000,'Deferred to week 14 in action case']]);a.getRange('F8:H16').format.columnWidth=28;a.getRange('G9:G16').format.font.color='#0759e6';v(a,'C25','Week 1 starts 5-Oct-2026. No financing availability is assumed.');a.getRange('C25:K26').merge();a.getRange('C25:K26').format.wrapText=true;v(a,'C28','Action changes timing only. Deferred capex remains a week-14 obligation.');a.getRange('C28:K29').merge();a.getRange('C28:K29').format.wrapText=true;
let invoices=Array.from({length:26},(_,i)=>{let week=Math.floor(i/2)+1;return ['INV-'+(1001+i),'Synthetic account '+(i%5+1),week,44000+(i%4)*3000,week===4||week===5?1:0,null,null,null];});table(iv,'C6:J32',[['Invoice ID','Account','Base week','USD amount','Eligible acceleration','Active week','Receipt date','At-risk aging'],...invoices]);for(let i=0;i<26;i++){let row=7+i;f(iv,'H'+row,`=MAX(1,E${row}+'Assumptions'!$D$8-G${row}*'Assumptions'!$D$13)`);f(iv,'I'+row,`=DATE(2026,10,5)+7*(H${row}-1)`);v(iv,'J'+row,i>=6&&i<=9?'Overdue at opening':'Current at opening');}iv.getRange('F7:F32').setNumberFormat(money);iv.getRange('I7:I32').setNumberFormat('mm/dd/yy');iv.getRange('C6:J32').format.columnWidth=23;table(iv,'K6:L6',[['Original due date','Days past due at 5-Oct']]);for(let i=0;i<26;i++){let rr=7+i,wk=Math.floor(i/2)+1;v(iv,'K'+rr,new Date(Date.UTC(2026,9,wk===4?(-9):wk===5?(-2):5+7*(wk-1))));f(iv,'L'+rr,`=MAX(0,DATE(2026,10,5)-K${rr})`);}iv.getRange('K7:K32').setNumberFormat('mm/dd/yy');iv.getRange('L7:L32').setNumberFormat('0');iv.getRange('K6:L32').format.columnWidth=24;v(iv,'C35','All 26 invoices are open at forecast start. Eligible invoices need collection consent.');iv.getRange('C35:K36').merge();iv.getRange('C35:K36').format.wrapText=true;
let names=['Opening cash','Open invoice collections','Direct cash sales','Total receipts','Payroll','Fuel','Supplier payments','Lease payments','Capex','Total payments','Net cash flow','Ending cash before financing','Minimum cash','Cumulative funding shortfall'];names.forEach((x,i)=>v(b,'C'+(7+i),x));for(let i=0;i<13;i++){let c=col(4+i),prev=col(3+i),wk=i+1;v(b,c+'5',wk);v(b,c+'6',new Date(Date.UTC(2026,9,5+7*i)));b.getRange(c+'6').setNumberFormat('d-mmm');f(b,c+'7',i===0?"='Assumptions'!G9":`=${prev}18`);f(b,c+'8',`=SUMIFS('Invoices'!$F$7:$F$32,'Invoices'!$H$7:$H$32,${c}$5)`);f(b,c+'9',"='Assumptions'!$G$11");f(b,c+'10',`=SUM(${c}8:${c}9)`);for(let j=0;j<4;j++)f(b,c+(11+j),`='Assumptions'!$G$${12+j}`);f(b,c+'15',`=IF(${c}$5='Assumptions'!$D$18,'Assumptions'!$G$16,0)`);f(b,c+'16',`=SUM(${c}11:${c}15)`);f(b,c+'17',`=${c}10-${c}16`);f(b,c+'18',`=SUM(${c}7,${c}17)`);f(b,c+'19',"='Assumptions'!$G$10");f(b,c+'20',`=MAX(0,${c}19-${c}18)`);}b.getRange('D7:P20').setNumberFormat(money);b.getRange('D18:P18').conditionalFormats.addCustom('D18<D19',{fill:'#fee2e2',font:{color:'#b91c1c',bold:true}});b.freezePanes.freezeRows(6);b.freezePanes.freezeColumns(3);v(b,'C23','Funding shortfall is a requirement, not an assumed available credit line.');b.getRange('C23:L24').merge();b.getRange('C23:L24').format.wrapText=true;
table(s,'C6:E12',[['Metric','Value','Basis'],['Lowest weekly cash',null,'Before financing'],['Funding needed to maintain floor',null,'Peak cumulative gap'],['Ending cash',null,'Week 13'],['Open invoices beyond horizon',null,'Carry-forward, not lost'],['Capex beyond horizon',null,'Future obligation'],['Opening overdue receivables',null,'Eligible collection queue']]);f(s,'D7',"=MIN('Weekly'!D18:P18)");f(s,'D8',"=MAX('Weekly'!D20:P20)");f(s,'D9',"='Weekly'!P18");f(s,'D10',"=SUMIFS('Invoices'!F7:F32,'Invoices'!H7:H32,\">13\")");f(s,'D11',"=IF('Assumptions'!D18>13,'Assumptions'!G16,0)");f(s,'D12',"=SUMIFS('Invoices'!F7:F32,'Invoices'!G7:G32,1)");s.getRange('D7:D12').setNumberFormat(money);s.getRange('E6:E12').format.columnWidth=26;
table(s,'C16:E29',[['Week','Ending cash','Minimum floor'],...Array.from({length:13},(_,i)=>['W'+(i+1),null,null])]);for(let i=0;i<13;i++){f(s,'D'+(17+i),`='Weekly'!${col(4+i)}18`);f(s,'E'+(17+i),`='Weekly'!${col(4+i)}19`);}s.getRange('D17:E29').setNumberFormat(money);let cashChart=chart(s,'C16:E29','Weekly cash before financing (USD)','line','H8','O23');cashChart.yAxis={numberFormatCode:'$0,"k"',numberFormatSourceLinked:false,textStyle:{typeface:'Arial',fontSize:11}};v(s,'H25','Accelerate eligible collections with consent. Defer capex only after review.');s.getRange('H25:O27').merge();s.getRange('H25:O27').format.wrapText=true;
table(r,'C6:J10',[['Week','Baseline receipts','Simulated receipts','Receipt variance','Baseline payments','Simulated payments','Payment variance','Net cash variance'],...[1,2,3,4].map(x=>[x,null,null,null,null,null,null,null])]);let baseReceipts=[111000,123000,111000,123000],pay=[112000,112000,112000,112000];for(let i=0;i<4;i++){let row=7+i;v(r,'D'+row,baseReceipts[i]);v(r,'E'+row,[101000,128000,111000,118000][i]);f(r,'F'+row,`=E${row}-D${row}`);v(r,'G'+row,pay[i]);v(r,'H'+row,[114000,111000,112000,113000][i]);f(r,'I'+row,`=H${row}-G${row}`);f(r,'J'+row,`=F${row}-I${row}`);}r.getRange('D7:J10').setNumberFormat(money);v(r,'C13','Frozen baseline, simulated observations. Review is not tied to active case.');r.getRange('C13:L14').merge();r.getRange('C13:L14').format.wrapText=true;v(r,'C17','Net cash variance');f(r,'D17','=SUM(J7:J10)');v(r,'C18','Absolute receipt error / baseline receipts');f(r,'D18','=(ABS(F7)+ABS(F8)+ABS(F9)+ABS(F10))/SUM(D7:D10)');r.getRange('D18').setNumberFormat('0.0%');
actions(w,[['Verify bank and invoice opening balances','Treasury + AR','Day 1','Opening bank / AR reconciled','Treasury lead'],['Collect eligible overdue invoices','AR + Account lead','Week 2','Customer consent and cash receipt','Credit lead'],['Review capex timing','Operations + Finance','Before week 6','Operational impact of deferral','Finance lead'],['Arrange liquidity contingency','Treasury','Before floor breach','Confirmed facility and covenants','Treasury lead'],['Refresh receipts / payments','Treasury + AP','Every Monday','Prior week actuals reconciled','Finance lead']]);terminal(w,[['Invoices collected plus carried forward',"=SUM('Invoices'!F7:F32)-SUM('Weekly'!D8:P8)-'Summary'!D10"],['Cash roll-forward',"='Weekly'!P18-'Assumptions'!G9-SUM('Weekly'!D17:P17)"],['Capex paid plus future obligation',"='Assumptions'!G16-SUM('Weekly'!D15:P15)-'Summary'!D11"],['Simulated review bridge',"=SUM('Review'!J7:J10)-SUM('Review'!F7:F10)+SUM('Review'!I7:I10)"]]);await finish(w,'Cash_Working_Capital',{minCash:['Summary','D7'],fundingGap:['Summary','D8'],endingCash:['Summary','D9'],futureReceipts:['Summary','D10'],deferredCapex:['Summary','D11'],overdue:['Summary','D12']});}
await fs.writeFile(out+'/scenario_captures.json',JSON.stringify(captures,null,2));await fs.writeFile(out+'/authoring_audit.json',JSON.stringify(evidence,null,2));
