import fs from 'node:fs/promises';
import {Workbook,SpreadsheetFile} from '@oai/artifact-tool';
const root=process.env.QUINCY_FINANCE_DIR || process.cwd(), out=root;
await fs.mkdir(out,{recursive:true});
const money='$'+'#,##0;($#,##0);"-"', num='#,##0;(#,##0);"-"';
const captures={}, evidence=[], caseNames=new Map();
const col=n=>String.fromCharCode(64+n);
function sheet(w,name,title,cols=12){let s=w.worksheets.add(name);s.showGridLines=false;s.getRange(`A1:${col(cols)}65`).format.font={name:'Arial',size:11,color:'#172c43'};s.getRange('A1:B65').format.columnWidth=3;s.getRange(`C1:C65`).format.columnWidth=42;s.getRange(`D1:${col(cols)}65`).format.columnWidth=17;s.getRange(`C1:${col(cols)}65`).format.rowHeight=22;s.getRange('C2').values=[[title]];s.getRange('C2').format.font={size:16,bold:true,color:'#17324d'};s.getRange(`C3:${col(cols)}3`).format.borders={bottom:{style:'thin',color:'#9bafc4'}};return s;}
function v(s,a,val){s.getRange(a).values=[[val]];if(typeof val==='number')s.getRange(a).format.font.color='#0759e6';}
function f(s,a,formula){s.getRange(a).formulas=[[formula]];s.getRange(a).format.font.color=formula.includes('!')?'#087a55':'#111111';}
function table(s,range,rows){s.getRange(range).values=rows;s.getRange(range).format.wrapText=true;s.getRange(range).format.autofitRows();let h=s.getRange(range).getRow(0);h.format.fill='#17324d';h.format.font={bold:true,color:'#ffffff'};h.format.horizontalAlignment='center';}
function caseControl(a,names=['Base','Downside','Upside']){caseNames.set(a,names);v(a,'C5','Case selected');v(a,'D5',1);a.getRange('D5').dataValidation={rule:{type:'list',values:['1','2','3']}};v(a,'F5',names.map((x,i)=>(i+1)+' '+x).join(' / '));a.getRange('F5:K6').merge();a.getRange('F5:K6').format.wrapText=true;f(a,'D4',`=CHOOSE(D5,${names.map(x=>'"'+x+'"').join(',')})`);}
function selected(s){v(s,'C4','Case selected');f(s,'D4',"='Assumptions'!D4");s.getRange('D4:F4').merge();}
function driver(a,row,name,base,down,up,fmt='0.0%'){v(a,`C${row}`,name+' (active)');f(a,`D${row}`,`=IF(ISNUMBER(CHOOSE($D$5,D${row+1},D${row+2},D${row+3})),CHOOSE($D$5,D${row+1},D${row+2},D${row+3}),NA())`);for(let i=0;i<3;i++){v(a,`C${row+i+1}`,caseNames.get(a)[i]);v(a,`D${row+i+1}`,[base,down,up][i]);}a.getRange(`D${row}:D${row+3}`).setNumberFormat(fmt);a.getRange(`C${row}:D${row}`).format.fill='#eaf1f8';}
function chart(s,range,title,type='line',from='H8',to='O23'){let c=s.charts.add(type,s.getRange(range));c.title=title;c.titleTextStyle.typeface='Arial';c.titleTextStyle.fontSize=14;c.hasLegend=true;c.xAxis={axisType:'textAxis',textStyle:{typeface:'Arial',fontSize:11}};c.yAxis={numberFormatCode:'$0.0,,"M"',numberFormatSourceLinked:false,textStyle:{typeface:'Arial',fontSize:11}};c.setPosition(from,to);c.series.items.forEach((x,i)=>{x.fill=['#17324d','#15a6ac','#a95f18'][i%3];x.line={fill:['#17324d','#15a6ac','#a95f18'][i%3],style:'solid',width:2};});return c;}
function actions(w,rows){let s=sheet(w,'Actions','Decision ownership and approval');table(s,'C6:I'+(6+rows.length),[['Action','Proposed owner','Due from approval','Trigger / evidence','Approval needed','Status','Evidence link'],...rows.map(r=>[...r,'Proposed',''])]);s.getRange('C6:I'+(6+rows.length)).format.columnWidth=27;s.getRange('H7:H'+(6+rows.length)).dataValidation={rule:{type:'list',values:['Proposed','In progress','Completed','Blocked']}};v(s,'C4','Roles and deadlines are proposed within a synthetic case.');s.getRange('C4:I4').merge();s.freezePanes.freezeRows(6);return s;}
function terminal(w,rows){let s=sheet(w,'Audit','Reconciliation checks');table(s,'C6:E'+(6+rows.length),[['Check','Difference','Tolerance (USD)'],...rows.map(r=>[r[0],null,r[2]??0.01])]);rows.forEach((r,i)=>f(s,'D'+(7+i),r[1]));s.getRange('D7:E'+(6+rows.length)).setNumberFormat('0.00');s.getRange('D7:D'+(6+rows.length)).format.font.color='#172c43';s.getRange('D7:D'+(6+rows.length)).conditionalFormats.addCustom('ABS(D7)>E7',{fill:'#fee2e2',font:{bold:true,color:'#b91c1c'}});return s;}
function upgradeOperating(w){
 const a=w.worksheets.getItem('Assumptions'), m=w.worksheets.getItem('Monthly'), s=w.worksheets.getItem('Summary');
 let wc=sheet(w,'Working Capital','Collections and supplier payments'),debt=sheet(w,'Debt','Debt and interest'),st=sheet(w,'Statements','Forecast statements and balance sheet');
 [wc,debt,st].forEach(selected);
 table(a,'F40:H58',[
 ['Expanded driver','Value','Synthetic opening / policy assumption'],
 ['Opening AR',1020000,'Outstanding credit sales'],['Opening AR collected in July',550000,'Remaining balance collected August'],
 ['Current-month collection fraction',.25,'Credit sales'],['Next-month collection fraction',.65,'Credit sales; remainder month two'],
 ['Opening AP',300000,'Paid July'],['Current-month supplier payment fraction',.5,'Variable costs; remainder next month'],
 ['Opening gross PP&E',1200000,'June 30'],['Opening accumulated depreciation',480000,'June 30'],
 ['New asset useful life (months)',60,'Month-end additions depreciate next month'],['Opening debt',600000,'June 30'],
 ['Annual debt interest',.08,'Opening monthly principal basis'],['Monthly principal repayment',10000,'No new borrowing'],
 ['Share capital',500000,'No issuance or dividends'],['Opening tax losses',0,'Forecast-only simplified tax-loss pool'],
 ['Tax rate',.25,'Positive income after loss offset'],['Opening cash',500000,'June 30 bank assumption'],
 ['Monthly capex',25000,'Paid at month-end'],['Existing monthly depreciation',20000,'Remaining old asset basis capped']]);
 a.getRange('F40:H58').format.columnWidth=32;a.getRange('G41:G58').format.font.color='#0759e6';a.getRange('G43:G44').setNumberFormat('0.0%');a.getRange('G46').setNumberFormat('0.0%');a.getRange('G51').setNumberFormat('0.0%');a.getRange('G55').setNumberFormat('0.0%');
 a.getRange('F8:I15').clear({applyTo:'all'});
 v(a,'F8','Cash assumptions are in the expanded driver block below.');a.getRange('F8:I10').merge();a.getRange('F8:I10').format.wrapText=true;
 v(a,'C31','Expanded schedules use explicit collection lags, debt and asset balances.');
 const wcl={7:'Credit revenue',8:'Current-month collections',9:'Prior-month collections',10:'Two-month prior collections',11:'Opening AR collections',12:'Total receipts',13:'Opening AR',14:'Closing AR',16:'Supplier purchases',17:'Current-month payments',18:'Prior-month payments',19:'Opening AP payment',20:'Total supplier payments',21:'Opening AP',22:'Closing AP'};
 const dl={7:'Opening debt',8:'Annual interest rate',9:'Interest expense / cash paid',10:'Principal repayment',11:'Closing debt'};
 const sl={7:'Revenue',8:'Variable costs',9:'Fixed cost',10:'Opex',11:'EBITDA',12:'Existing asset depreciation',13:'New asset depreciation',14:'Total depreciation',15:'EBIT',16:'Interest expense',17:'Pretax income',18:'Opening tax losses',19:'Tax losses used',20:'Taxable income',21:'Cash tax / expense',22:'Closing tax losses',23:'Net income',26:'Opening cash',27:'Net income',28:'Depreciation add-back',29:'Change in AR',30:'Change in AP',31:'Operating cash flow',32:'Cash capex',33:'Debt principal repayment',34:'Net change in cash',35:'Closing cash',38:'Cash',39:'AR',40:'Gross PP&E',41:'Accumulated depreciation',42:'Net PP&E',43:'Total assets',45:'AP',46:'Debt',47:'Total liabilities',49:'Share capital',50:'Opening retained earnings',51:'Net income to retained earnings',52:'Closing retained earnings',53:'Total equity',54:'Liabilities and equity',55:'Balance sheet difference'};
 for(const [sht,labels] of [[wc,wcl],[debt,dl],[st,sl]])for(const [r,l]of Object.entries(labels))v(sht,'C'+r,l);
 for(let k=0;k<6;k++){
  let c=col(4+k),p=col(3+k),mc=col(10+k);for(const sht of [wc,debt,st]){v(sht,c+'6',new Date(Date.UTC(2026,6+k,1)));sht.getRange(c+'6').setNumberFormat('mmm-yy');}
  f(wc,c+'7',`='Monthly'!${mc}7`);f(wc,c+'8',`=${c}7*'Assumptions'!$G$43`);
  f(wc,c+'9',k>0?`=${p}7*'Assumptions'!$G$44`:'=0');
  f(wc,c+'10',k>1?`=${col(2+k)}7*(1-SUM('Assumptions'!$G$43:$G$44))`:'=0');
  f(wc,c+'11',k===0?"='Assumptions'!G42":k===1?"='Assumptions'!G41-'Assumptions'!G42":'=0');
  f(wc,c+'12',`=SUM(${c}8:${c}11)`);f(wc,c+'13',k===0?"='Assumptions'!G41":`=${p}14`);f(wc,c+'14',`=${c}13+${c}7-${c}12`);
  f(wc,c+'16',`='Monthly'!${mc}8`);f(wc,c+'17',`=${c}16*'Assumptions'!$G$46`);f(wc,c+'18',k>0?`=${p}16*(1-'Assumptions'!$G$46)`:'=0');f(wc,c+'19',k===0?"='Assumptions'!G45":'=0');f(wc,c+'20',`=SUM(${c}17:${c}19)`);f(wc,c+'21',k===0?"='Assumptions'!G45":`=${p}22`);f(wc,c+'22',`=${c}21+${c}16-${c}20`);
  f(debt,c+'7',k===0?"='Assumptions'!G50":`=${p}11`);f(debt,c+'8',"='Assumptions'!$G$51");f(debt,c+'9',`=${c}7*${c}8/12`);f(debt,c+'10',`=MIN(${c}7,'Assumptions'!$G$52)`);f(debt,c+'11',`=${c}7-${c}10`);
  for(const r of [7,8,9,10,11])f(st,c+r,`='Monthly'!${mc}${r}`);
  f(st,c+'12',`=MIN('Assumptions'!$G$58,MAX(0,'Assumptions'!$G$47-'Assumptions'!$G$48-${k}*'Assumptions'!$G$58))`);
  f(st,c+'13',k===0?'=0':`=SUM(D32:${p}32)/'Assumptions'!$G$49`);f(st,c+'14',`=SUM(${c}12:${c}13)`);f(st,c+'15',`=${c}11-${c}14`);f(st,c+'16',`='Debt'!${c}9`);f(st,c+'17',`=${c}15-${c}16`);
  f(st,c+'18',k===0?"='Assumptions'!G54":`=${p}22`);f(st,c+'19',`=MIN(${c}18,MAX(0,${c}17))`);f(st,c+'20',`=MAX(0,${c}17-${c}19)`);f(st,c+'21',`=${c}20*'Assumptions'!$G$55`);f(st,c+'22',`=${c}18-${c}19+MAX(0,-${c}17)`);f(st,c+'23',`=${c}17-${c}21`);
  f(st,c+'26',k===0?"='Assumptions'!G56":`=${p}35`);f(st,c+'27',`=${c}23`);f(st,c+'28',`=${c}14`);f(st,c+'29',`='Working Capital'!${c}14-'Working Capital'!${c}13`);f(st,c+'30',`='Working Capital'!${c}22-'Working Capital'!${c}21`);f(st,c+'31',`=SUM(${c}27:${c}28)-${c}29+${c}30`);f(st,c+'32',"='Assumptions'!$G$57");f(st,c+'33',`='Debt'!${c}10`);f(st,c+'34',`=${c}31-SUM(${c}32:${c}33)`);f(st,c+'35',`=SUM(${c}26,${c}34)`);
  f(st,c+'38',`=${c}35`);f(st,c+'39',`='Working Capital'!${c}14`);f(st,c+'40',k===0?`='Assumptions'!G47+${c}32`:`=${p}40+${c}32`);f(st,c+'41',k===0?`='Assumptions'!G48+${c}14`:`=${p}41+${c}14`);f(st,c+'42',`=${c}40-${c}41`);f(st,c+'43',`=SUM(${c}38:${c}39,${c}42)`);f(st,c+'45',`='Working Capital'!${c}22`);f(st,c+'46',`='Debt'!${c}11`);f(st,c+'47',`=SUM(${c}45:${c}46)`);f(st,c+'49',"='Assumptions'!$G$53");
  f(st,c+'50',k===0?"=SUM('Assumptions'!G56,'Assumptions'!G41,'Assumptions'!G47)-SUM('Assumptions'!G48,'Assumptions'!G45,'Assumptions'!G50,'Assumptions'!G53)":`=${p}52`);f(st,c+'51',`=${c}23`);f(st,c+'52',`=SUM(${c}50:${c}51)`);f(st,c+'53',`=SUM(${c}49,${c}52)`);f(st,c+'54',`=SUM(${c}47,${c}53)`);f(st,c+'55',`=${c}43-${c}54`);
  for(const [r,sn,sr]of [[13,'Statements',14],[14,'Statements',15],[15,'Statements',21],[16,'Working Capital',14],[17,'Working Capital',22],[19,'Statements',32],[20,'Statements',34],[21,'Statements',26],[22,'Statements',35]])f(m,mc+r,`='${sn}'!${c}${sr}`);
  f(m,mc+'18',`='Statements'!${c}29-'Statements'!${c}30`);
 }
 [wc,debt,st].forEach(x=>{x.getRange('D7:I55').setNumberFormat(money);x.freezePanes.freezeRows(6);x.freezePanes.freezeColumns(3);});debt.getRange('D8:I8').setNumberFormat('0.0%');st.getRange('D55:I55').setNumberFormat('0.00');
 v(st,'C59','Simplified tax-loss offsets assume full usability. No deferred tax assets, inventory or dividends.');st.getRange('C59:I61').merge();st.getRange('C59:I61').format.wrapText=true;
 v(wc,'C26','Opening AR uses two dated collection buckets. Sales collect 25% / 65% / 10%.');wc.getRange('C26:K27').merge();wc.getRange('C26:K27').format.wrapText=true;
 v(s,'H27','Synthetic case. Statements include AR/AP lags, PP&E, debt, interest and tax losses.');v(m,'C20','Net change in cash after principal');
}

function upgradeFleet(w){
 const a=w.worksheets.getItem('Assumptions'),b=w.worksheets.getItem('Cash Flows'),s=w.worksheets.getItem('Summary');
 const tx=sheet(w,'After Tax','After-tax unlevered alternatives'),fin=sheet(w,'Financing','Purchase financing and lease obligations');[tx,fin].forEach(selected);
 table(a,'F43:H57',[['Expanded driver','Value','Synthetic assumption'],['Tax rate',.25,'Immediate use of deductions assumed'],['Old tax basis / vehicle',15000,'Remaining depreciable basis'],['New tax residual / vehicle',0,'Five-year straight-line tax depreciation'],['Transition cash / vehicle',4000,'Replacement / lease commissioning; deductible'],['Lease included miles / vehicle',65000,'Annual allowance'],['Excess mileage charge',.2,'USD per excess mile'],['Debt fraction of new purchase',.7,'Assumed loan; not approved'],['Annual debt rate',.075,'Five-year level principal'],['Debt origination fee',.01,'Upfront financing cost'],['Lease accounting discount',.075,'Annual end-of-year payments'],['Lease non-deductible deposit',50000,'Returned at year five'],['Tax depreciation years',5,'No bonus depreciation'],['Transition deduction fraction',1,'Sensitivity input'],['Tax usable fraction',1,'Set zero when deductions unusable']]);a.getRange('F43:H57').format.columnWidth=32;a.getRange('G44:G57').format.font.color='#0759e6';
 const labels={7:'Keep operating cash costs',8:'Keep tax depreciation',9:'Keep tax benefit',10:'Keep after-tax terminal value',11:'Keep unlevered cash flow',14:'Replace operating cash costs',15:'Replace tax depreciation',16:'Replace tax benefit',17:'Replace after-tax terminal value',18:'Replace unlevered cash flow',21:'Lease rental / fuel / downtime',22:'Excess mileage cost',23:'Lease tax benefit',24:'Lease deposit returned',25:'Lease unlevered cash flow',28:'Discount factor',29:'Keep present value',30:'Replace present value',31:'Lease present value',34:'Replacement vs keep cash flow',35:'Lease vs keep cash flow'};
 for(const [r,l]of Object.entries(labels))v(tx,'C'+r,l);
 for(let y=0;y<=5;y++){let c=col(4+y),p=col(3+y);v(tx,c+'6',y);v(fin,c+'6',y);
  if(y===0){f(tx,c+'11','=0');f(tx,c+'18',"='Cash Flows'!D20-('Assumptions'!G9*('Assumptions'!G11-'Assumptions'!G45))*'Assumptions'!G44-'Assumptions'!G9*'Assumptions'!G47*(1-'Assumptions'!G44*'Assumptions'!G56*'Assumptions'!G57)");f(tx,c+'25',"='Cash Flows'!D28-('Assumptions'!G9*('Assumptions'!G11-'Assumptions'!G45))*'Assumptions'!G44-'Assumptions'!G9*'Assumptions'!G47*(1-'Assumptions'!G44*'Assumptions'!G56*'Assumptions'!G57)");}
  else{f(tx,c+'7',`='Cash Flows'!${c}10`);f(tx,c+'8',"='Assumptions'!$G$9*'Assumptions'!$G$45/'Assumptions'!$G$55");f(tx,c+'9',`=SUM(${c}7:${c}8)*'Assumptions'!$G$44*'Assumptions'!$G$57`);f(tx,c+'10',y===5?"='Cash Flows'!I11*(1-'Assumptions'!G44)":'=0');f(tx,c+'11',`=-${c}7+SUM(${c}9:${c}10)`);
  f(tx,c+'14',`='Cash Flows'!${c}18`);f(tx,c+'15',"='Assumptions'!$G$9*('Assumptions'!$G$10-'Assumptions'!$G$46)/'Assumptions'!$G$55");f(tx,c+'16',`=SUM(${c}14:${c}15)*'Assumptions'!$G$44*'Assumptions'!$G$57`);f(tx,c+'17',y===5?"='Cash Flows'!I19-('Cash Flows'!I19-'Assumptions'!G9*'Assumptions'!G46)*'Assumptions'!G44":'=0');f(tx,c+'18',`=-${c}14+SUM(${c}16:${c}17)`);
  f(tx,c+'21',`='Cash Flows'!${c}26`);f(tx,c+'22',"=MAX(0,'Assumptions'!$D$18-'Assumptions'!$G$48)*'Assumptions'!$G$49*'Assumptions'!$G$9");f(tx,c+'23',`=SUM(${c}21:${c}22)*'Assumptions'!$G$44*'Assumptions'!$G$57`);f(tx,c+'24',y===5?"='Cash Flows'!I27":'=0');f(tx,c+'25',`=-SUM(${c}21:${c}22)+SUM(${c}23:${c}24)`);}
  f(tx,c+'28',`='Cash Flows'!${c}34`);for(const [r,cf]of [[29,11],[30,18],[31,25]])f(tx,c+r,`=${c}${cf}*${c}28`);f(tx,c+'34',`=${c}18-${c}11`);f(tx,c+'35',`=${c}25-${c}11`);
  f(fin,c+'7',y===0?'=0':y===1?"='Assumptions'!G9*'Assumptions'!G10*'Assumptions'!G50":`=${p}10`);f(fin,c+'8',y===0?"='Assumptions'!G9*'Assumptions'!G10*'Assumptions'!G50":'=0');f(fin,c+'9',y===0?'=0':`=MIN(${c}7,$D$8/5)`);f(fin,c+'10',`=SUM(${c}7:${c}8)-${c}9`);f(fin,c+'11',y===0?'=0':`=${c}7*'Assumptions'!$G$51`);f(fin,c+'12',y===0?"=D8*'Assumptions'!G52":'=0');f(fin,c+'13',`=${c}11*'Assumptions'!$G$44*'Assumptions'!$G$57`);f(fin,c+'14',`='After Tax'!${c}18+${c}8-${c}9-${c}11-${c}12+${c}13`);
  f(fin,c+'17',y===0?"=NPV('Assumptions'!G53,'Cash Flows'!E23:I23)":`=${p}20`);f(fin,c+'18',y===0?'=0':`=${c}17*'Assumptions'!$G$53`);f(fin,c+'19',y===0?'=0':`='Cash Flows'!${c}23`);f(fin,c+'20',y===0?`=${c}17`:`=SUM(${c}17:${c}18)-${c}19`);
 }
 const fl={7:'Opening purchase loan',8:'Loan draw',9:'Principal repayment',10:'Closing purchase loan',11:'Cash interest',12:'Origination fee',13:'Interest tax benefit',14:'Replace equity cash flow',17:'Opening lease liability',18:'Lease liability interest',19:'Contract rental payment',20:'Closing lease liability'};for(const [r,l]of Object.entries(fl))v(fin,'C'+r,l);
 tx.getRange('D7:I35').setNumberFormat(money);tx.getRange('D28:I28').setNumberFormat('0.000');fin.getRange('D7:I20').setNumberFormat(money);
 v(fin,'C24','Loan cash flows are separate from unlevered NPV. Lease liability is a simplified obligation roll-forward.');fin.getRange('C24:K26').merge();fin.getRange('C24:K26').format.wrapText=true;
 for(let i=0;i<3;i++){let r=7+i;f(s,'D'+r,`=-SUM('After Tax'!D${29+i}:I${29+i})`);f(s,'E'+r,`=MAX(0,-'After Tax'!D${[11,18,25][i]})`);}
 v(s,'C13','Recommended within budget');v(s,'D6','After-tax PV costs');s.charts.items[0].setData(s.getRange('C6:D9'));s.charts.items[0].title='Five-year after-tax present value (USD)';v(s,'C26','After-tax unlevered NPV. Separate financing schedule; assumed full tax usability.');s.getRange('C26:O27').format.wrapText=true;v(a,'C38','Synthetic appraisal. Tax basis, transition and lease mileage are explicit.');
 const review=w.worksheets.getItem('Review');v(review,'C13','Legacy simulated observations are preserved. The $660k target uses the original pre-tax scope.');
}

function upgradeCash(w){
 const a=w.worksheets.getItem('Assumptions'),b=w.worksheets.getItem('Weekly'),s=w.worksheets.getItem('Summary');
 const nc=sheet(w,'New Invoices','Synthetic invoices issued during forecast',12);selected(nc);
 table(a,'F34:H43',[['Expanded driver','Value','Synthetic assumption'],['Facility limit',200000,'Hypothetical undrawn revolver; not approved'],['Annual facility rate',.09,'Opening weekly debt basis'],['Commitment fee',.005,'Annual on unused opening commitment'],['Opening facility debt',0,'Week 1'],['Weekly credit billings',92000,'Separate from opening AR and cash sales'],['Credit collection lag weeks',2,'Active scenario adds receipt delay'],['Forecast weeks',26,'Includes deferred capex week 14'],['Auto-repayment',1,'Repay excess above floor'],['Unfunded cash floor',100000,'Matches management minimum']]);a.getRange('F34:H43').format.columnWidth=32;a.getRange('G35:G43').format.font.color='#0759e6';
 v(a,'C25','Week 1 starts 5-Oct-2026. Facility availability is a hypothetical input.');v(s,'C2','26-week liquidity and funding');
 table(nc,'C6:H32',[['Invoice ID','Issue week','Amount USD','Collection week','Collection date','Opening AR?'],...Array.from({length:26},(_,i)=>['NEW-'+(2001+i),i+1,null,null,null,'No'])]);for(let i=0;i<26;i++){let r=7+i;f(nc,'E'+r,"='Assumptions'!$G$39");f(nc,'F'+r,`=D${r}+'Assumptions'!$G$40+'Assumptions'!$D$8`);f(nc,'G'+r,`=DATE(2026,10,5)+7*(F${r}-1)`);}nc.getRange('E7:E32').setNumberFormat(money);nc.getRange('G7:G32').setNumberFormat('mm/dd/yy');nc.getRange('C6:H32').format.columnWidth=24;
 b.getRange('C23:L24').unmerge();b.getRange('C23:L24').clear({applyTo:'contents'});
 const labels={7:'Opening funded cash',8:'Opening invoice receipts',9:'Direct cash sales',10:'New invoice receipts',11:'Total receipts',12:'Payroll',13:'Fuel',14:'Supplier payments',15:'Lease payments',16:'Capex',17:'Total operating payments',18:'Operating net cash flow',19:'Opening facility debt',20:'Interest on opening debt',21:'Undrawn commitment fee',22:'Cash before draw / repayment',23:'Available commitment',24:'Facility draw',25:'Facility repayment',26:'Closing facility debt',27:'Closing funded cash',28:'Minimum cash floor',29:'Residual funding shortfall',30:'Unfunded cash without facility',31:'Cumulative net funding costs'};for(const [r,l]of Object.entries(labels))v(b,'C'+r,l);
 const letter=n=>{let s='';while(n>0){n--;s=String.fromCharCode(65+n%26)+s;n=Math.floor(n/26);}return s;};
 b.getRange('D1:AC35').format.columnWidth=17;b.getRange('C7:C31').format.columnWidth=43;
 for(let i=0;i<26;i++){let c=letter(4+i),p=letter(3+i),wk=i+1;v(b,c+'5',wk);v(b,c+'6',new Date(Date.UTC(2026,9,5+7*i)));b.getRange(c+'6').setNumberFormat('d-mmm');f(b,c+'7',i===0?"='Assumptions'!G9":`=${p}27`);f(b,c+'8',`=SUMIFS('Invoices'!$F$7:$F$32,'Invoices'!$H$7:$H$32,${c}$5)`);f(b,c+'9',"='Assumptions'!$G$11");f(b,c+'10',`=SUMIFS('New Invoices'!$E$7:$E$32,'New Invoices'!$F$7:$F$32,${c}$5)`);f(b,c+'11',`=SUM(${c}8:${c}10)`);for(let j=0;j<4;j++)f(b,c+(12+j),`='Assumptions'!$G$${12+j}`);f(b,c+'16',`=IF(${c}$5='Assumptions'!$D$18,'Assumptions'!$G$16,0)`);f(b,c+'17',`=SUM(${c}12:${c}16)`);f(b,c+'18',`=${c}11-${c}17`);f(b,c+'19',i===0?"='Assumptions'!G38":`=${p}26`);f(b,c+'20',`=${c}19*'Assumptions'!$G$36/52`);f(b,c+'21',`=MAX(0,'Assumptions'!$G$35-${c}19)*'Assumptions'!$G$37/52`);f(b,c+'22',`=${c}7+${c}18-SUM(${c}20:${c}21)`);f(b,c+'23',`=MAX(0,'Assumptions'!$G$35-${c}19)`);f(b,c+'24',`=MIN(${c}23,MAX(0,'Assumptions'!$G$10-${c}22))`);f(b,c+'25',`=IF('Assumptions'!$G$42=1,MIN(${c}19,MAX(0,${c}22-'Assumptions'!$G$10)),0)`);f(b,c+'26',`=${c}19+${c}24-${c}25`);f(b,c+'27',`=${c}22+${c}24-${c}25`);f(b,c+'28',"='Assumptions'!$G$10");f(b,c+'29',`=MAX(0,${c}28-${c}27)`);f(b,c+'30',i===0?`='Assumptions'!G9+${c}18`:`=${p}30+${c}18`);f(b,c+'31',i===0?`=SUM(${c}20:${c}21)`:`=${p}31+SUM(${c}20:${c}21)`);}
 b.getRange('D7:AC31').setNumberFormat(money);b.getRange('D18:P18').conditionalFormats.clear();b.getRange('D27:AC27').conditionalFormats.addCustom('D27<D28',{fill:'#fee2e2',font:{color:'#b91c1c',bold:true}});
 v(s,'C7','Lowest funded cash');f(s,'D7',"=MIN('Weekly'!D27:AC27)");v(s,'C8','Peak facility debt');f(s,'D8',"=MAX('Weekly'!D26:AC26)");f(s,'D9',"='Weekly'!AC27");v(s,'E9','Week 26');f(s,'D10',"=SUMIFS('Invoices'!F7:F32,'Invoices'!H7:H32,\">26\")+SUMIFS('New Invoices'!E7:E32,'New Invoices'!F7:F32,\">26\")");f(s,'D11',"=IF('Assumptions'!D18>26,'Assumptions'!G16,0)");v(s,'E7','After facility flows');v(s,'E8','Assumed $200k limit');v(s,'C13','Residual funding shortfall');f(s,'D13',"=MAX('Weekly'!D29:AC29)");v(s,'C14','Unfunded minimum cash');f(s,'D14',"=MIN('Weekly'!D30:AC30)");s.getRange('D13:D14').setNumberFormat(money);
 s.getRange('C16:E42').values=[['Week','Funded cash','Minimum floor'],...Array.from({length:26},(_,i)=>['W'+(i+1),null,null])];for(let i=0;i<26;i++){let c=letter(i+4);f(s,'D'+(17+i),`='Weekly'!${c}27`);f(s,'E'+(17+i),`='Weekly'!${c}28`);}s.getRange('D17:E42').setNumberFormat(money);s.charts.items[0].setData(s.getRange('C16:E42'));s.charts.items[0].title='26-week funded cash (USD)';s.charts.items[0].yAxis={numberFormatCode:'$0.0,,"M"',numberFormatSourceLinked:false};v(s,'H25','Facility terms are hypothetical. Deferred capex is paid in week 14.');
}

function validateExpanded(w,slug){
 const a=w.worksheets.getItem('Assumptions');
 const limits=slug==='Operating_Plan'?Object.fromEntries(Array.from({length:18},(_,i)=>[41+i,'nonnegative'])):slug==='Fleet_Investment'?Object.fromEntries(Array.from({length:14},(_,i)=>[44+i,'nonnegative'])):Object.fromEntries(Array.from({length:9},(_,i)=>[35+i,'nonnegative']));
 const percent=slug==='Operating_Plan'?[43,44,46,51,55]:slug==='Fleet_Investment'?[44,50,51,52,53,56,57]:[36,37];
 for(const r of percent)limits[r]='percent';
 if(slug==='Operating_Plan')limits[49]='positive integer';
 if(slug==='Fleet_Investment')limits[55]='positive integer';
 if(slug==='Cash_Working_Capital'){limits[40]='integer';limits[42]='boolean';f(a,'G41','=26');v(a,'H41','Fixed 26-week build, not an editable horizon');f(a,'G43','=G10');v(a,'F43','Cash floor (linked)');v(a,'H43','Linked to the minimum cash input above');}
 const start=Math.min(...Object.keys(limits).map(Number));v(a,'I'+(start-1),'Validated value');a.getRange('I'+(start-1)).format.fill='#17324d';a.getRange('I'+(start-1)).format.font={color:'#ffffff',bold:true};
 for(const [row,kind] of Object.entries(limits)){
  const r=Number(row),g='G'+r;let conditions=[`ISNUMBER(${g})`,`${g}>=0`];
  if(kind==='percent'||kind==='boolean')conditions.push(`${g}<=1`);
  if(kind.includes('integer')||kind==='boolean')conditions.push(`MOD(${g},1)=0`);
  if(kind==='positive integer')conditions.push(`${g}>0`);
  if(slug==='Operating_Plan'&&[43,44].includes(r))conditions.push('ISNUMBER(G43)','ISNUMBER(G44)','G43+G44<=1');
  if(slug==='Operating_Plan'&&r===42)conditions.push('ISNUMBER(G41)','G42<=G41');
  if(slug==='Operating_Plan'&&r===48)conditions.push('ISNUMBER(G47)','G48<=G47');
  if(slug==='Cash_Working_Capital'&&r===38)conditions.push('ISNUMBER(G35)','G38<=G35');
  f(a,'I'+r,`=IF(AND(${conditions.join(',')}),${g},NA())`);a.getRange('I'+r).setNumberFormat(percent.includes(r)?'0.0%':kind.includes('integer')||kind==='boolean'?'0':money);
 }
 if(slug==='Fleet_Investment'){a.getRange('I48').setNumberFormat('#,##0');a.getRange('I49').setNumberFormat('$0.00');}
 if(slug==='Cash_Working_Capital'){a.getRange('I41').setNumberFormat('0');a.getRange('G9:G16').setNumberFormat(money);}
 // The owning control block validates inputs once. Builds link to validated cells.
 const cells=Object.keys(limits).join('|');
 // Explicit construction avoids accidental interpretation of the replacement list as literal source.
 const pattern=new RegExp("('Assumptions'!\\$?)G(\\$?)("+cells+")\\b",'g');
 for(const sh of w.worksheets.items){if(sh.name==='Assumptions')continue;const formulas=sh.getRange('A1:AC65').formulas;for(let r=0;r<formulas.length;r++)for(let c=0;c<formulas[r].length;c++){const old=formulas[r][c];if(typeof old!=='string'||!old.startsWith('='))continue;const prepared=old.replace(/('Assumptions'!\$?)G(\$?)(\d+):(\$?)G(\$?)(\d+)/g,(match,prefix,dollar,r1,dollar2,dollar3,r2)=>limits[r1]&&limits[r2]?prefix+'I'+dollar+r1+':'+dollar2+'I'+dollar3+r2:match);const updated=prepared.replace(pattern,'$1I$2$3');if(updated!==old){let cc=c+1,letter='';while(cc){cc--;letter=String.fromCharCode(65+cc%26)+letter;cc=Math.floor(cc/26);}sh.getRange(letter+(r+1)).formulas=[[updated]];}}}
}

async function finish(w,slug,metricCells,extraCheck){
for(const sh of w.worksheets.items){
 if(sh.name==='Assumptions'){
  if(slug==='Operating_Plan'){for(const r of [41,42,45,47,48,50,52,53,54,56,57,58])sh.getRange('G'+r).setNumberFormat(money);sh.getRange('G49').setNumberFormat('0');sh.getRange('G7').setNumberFormat('0.0%');sh.getRange('G8:G9').setNumberFormat(money);}
  if(slug==='Fleet_Investment'){for(const r of [44,50,51,52,53,56,57])sh.getRange('G'+r).setNumberFormat('0.0%');for(const r of [45,46,47,54])sh.getRange('G'+r).setNumberFormat(money);sh.getRange('G49').setNumberFormat('$0.00');sh.getRange('G48').setNumberFormat('#,##0');sh.getRange('G55').setNumberFormat('0');}
  if(slug==='Cash_Working_Capital'){for(const r of [35,38,39,43])sh.getRange('G'+r).setNumberFormat(money);sh.getRange('G36:G37').setNumberFormat('0.0%');sh.getRange('G40:G42').setNumberFormat('0');}
 }
 if(sh.name==='Detail'&&slug==='Operating_Plan')sh.getRange('M7:M42').setNumberFormat('0.00');
 if(sh.name==='Review'&&slug==='Cash_Working_Capital')sh.getRange('D17').setNumberFormat(money);
 if(sh.name==='Cash Flows'&&slug==='Fleet_Investment')v(sh,'C2','Pre-tax operating cash flows');
}
validateExpanded(w,slug);w.recalculate();let ass=w.worksheets.getItem('Assumptions');captures[slug]=[];for(let c=1;c<=3;c++){v(ass,'D5',c);w.recalculate();let vals={case:c,name:ass.getRange('D4').values[0][0]};for(const [k,[s,a]] of Object.entries(metricCells))vals[k]=w.worksheets.getItem(s).getRange(a).values[0][0];captures[slug].push(vals);}
v(ass,'D5',1);w.recalculate();if(extraCheck)await extraCheck(w);w.recalculate();let errors=await w.inspect({kind:'match',searchTerm:'#REF!|#DIV/0!|#VALUE!|#NAME\\?|#NUM!|#NULL!|#SPILL!|#CALC!|#N/A',options:{useRegex:true,maxResults:20},maxChars:3000});evidence.push({slug,errors:errors.ndjson,cases:captures[slug]});console.log(slug,JSON.stringify(captures[slug]),errors.ndjson);
for(const s of w.worksheets.items){if(s.name==='Statements')s.getRange('D7:I55').format.font.color='#172c43';if(s.name==='Summary'){s.getRange('D7:F15').format.font.color='#172c43';s.getRange('D17:F42').format.font.color='#172c43';}  const range=s.name==='Summary'?(slug==='Cash_Working_Capital'?'C1:O43':'C1:O29'):s.name==='Actions'?'C1:I12':s.name==='Detail'?'C1:N42':s.name==='Invoices'?'C1:L36':s.name==='Assumptions'?'C1:K61':s.name==='Cash Flows'?'C1:L42':s.name==='Weekly'?'C1:AC33':s.name==='Monthly'?'C1:O28':s.name==='Statements'?'C1:I61':s.name==='After Tax'?'C1:I37':s.name==='New Invoices'?'C1:H33':'C1:L28';let b=await w.render({sheetName:s.name,range,scale:1.5,format:'png'});await fs.writeFile(out+'/'+slug+'-'+s.name.replaceAll(' ','_')+'.png',new Uint8Array(await b.arrayBuffer()));}
let file=await SpreadsheetFile.exportXlsx(w);await file.save(out+'/'+slug+'.xlsx');}

// Operating plan: preserve the earlier portfolio case's 18 H1 synthetic records.
{
const w=Workbook.create();let sum=sheet(w,'Summary','Transportation operating plan (2026)',15),a=sheet(w,'Assumptions','Operating assumptions'),d=sheet(w,'Detail','Segment operating build',14),m=sheet(w,'Monthly','Monthly profit and cash forecast',15),b=sheet(w,'Variance','July EBITDA variance to reference plan'),src=sheet(w,'Source','Synthetic H1 source records',10);caseControl(a);[sum,d,m,b].forEach(selected);
driver(a,8,'Monthly unit growth',.012,-.012,.027);driver(a,13,'Monthly price growth',.018,0,.025);driver(a,18,'Monthly unit cost inflation',.025,.035,.020);driver(a,23,'Monthly operating expense growth',.020,.025,.018);
table(a,'F8:I15',[['Cash driver','Value','Units','Basis'],['Opening July cash',500000,'USD','Synthetic assumption'],['Receivable days',35,'days','30-day month approximation'],['Payable days',20,'days','Variable costs only'],['Monthly depreciation',20000,'USD','Existing asset base simplified'],['Monthly cash capex',25000,'USD','Maintenance capex assumption'],['Cash tax rate',.25,'fraction','Tax only on positive EBIT'],['Minimum cash',250000,'USD','Illustrative management threshold']]);a.getRange('G9:G15').format.font.color='#0759e6';a.getRange('F8:I15').format.columnWidth=23;v(a,'C31','Monthly rates compound. No financing, dividends, or loss carryforwards.');a.getRange('C31:K32').merge();a.getRange('C31:K32').format.wrapText=true;
let csv=await fs.readFile(root+'/source/synthetic_actuals_h1.csv','utf8');let lines=csv.trim().split(/\r?\n/).slice(1).map(x=>x.split(','));let raw=lines.map(x=>[new Date(x[0]+'-01T00:00:00Z'),x[1],...x.slice(2).map(Number)]);table(src,'C6:I24',[['Month','Segment','Units','Price / unit','Variable cost / unit','Fixed cost','Opex'],...raw]);src.getRange('C7:C24').setNumberFormat('mmm-yy');src.getRange('E7:I24').setNumberFormat(num);src.getRange('F7:G24').setNumberFormat('0.00');v(src,'C27','Source: existing fpa-forecast-scenario-planning synthetic_actuals_h1.csv.');src.getRange('C27:K28').merge();src.getRange('C27:K28').format.wrapText=true;
table(d,'C6:N6',[['Month','Segment','Units','Price / unit','Variable cost / unit','Fixed','Opex','Revenue','Variable cost','EBITDA','Seasonality','Original fixed']]);d.getRange('C7:C42').setNumberFormat('mmm-yy');d.getRange('E7:N42').setNumberFormat(money);d.getRange('E7:E42').setNumberFormat(num);d.getRange('F7:G42').setNumberFormat('0.00');let seasonal=[.94,.92,1,.98,1.02,1,1.01,1.04,1.01,1.08,1.13,1.17],orig=[89000,76000,42000];
for(let i=0;i<36;i++){let r=7+i,mo=Math.floor(i/3)+1,j=i%3;v(d,'C'+r,new Date(Date.UTC(2026,mo-1,1)));v(d,'D'+r,['Core','Enterprise','Services'][j]);v(d,'M'+r,seasonal[mo-1]);v(d,'N'+r,orig[j]);if(i<18){for(let c=5;c<=9;c++)f(d,col(c)+r,`='Source'!${col(c)}${r}`);}else{let june=22+j,k=mo-6;f(d,'E'+r,`=ROUND(E${june}*(1+'Assumptions'!$D$8)^${k}*M${r}/M${june},0)`);f(d,'F'+r,`=F${june}*(1+'Assumptions'!$D$13)^${k}`);f(d,'G'+r,`=G${june}*(1+'Assumptions'!$D$18)^${k}`);f(d,'H'+r,`=N${r}*(1+0.001*${mo})*(1+'Assumptions'!$D$18*0.35)^${k}`);let originalOpex=[61000,82000,51000][j];f(d,'I'+r,`='Source'!I${june}/(1+0.002*6)*(1+0.002*${mo})*(1+'Assumptions'!$D$23)^${k}`);}f(d,'J'+r,`=E${r}*F${r}`);f(d,'K'+r,`=E${r}*G${r}`);f(d,'L'+r,`=J${r}-SUM(K${r},H${r}:I${r})`);}
let ml=['Revenue','Variable cost','Fixed cost','Opex','EBITDA','EBITDA margin','Depreciation','EBIT','Cash taxes','Receivables','Payables','Change in net working capital','Cash capex','Operating cash after capex','Opening cash','Ending cash'];ml.forEach((x,i)=>v(m,'C'+(7+i),x));for(let k=0;k<12;k++){let c=col(4+k);v(m,c+'6',new Date(Date.UTC(2026,k,1)));m.getRange(c+'6').setNumberFormat('mmm-yy');[7,8,9,10,11].forEach((r,j)=>f(m,c+r,`=SUMIFS('Detail'!$${['J','K','H','I','L'][j]}$7:$${['J','K','H','I','L'][j]}$42,'Detail'!$C$7:$C$42,${c}$6)`));f(m,c+'12',`=${c}11/${c}7`);if(k>=6){f(m,c+'13',"='Assumptions'!$G$12");f(m,c+'14',`=${c}11-${c}13`);f(m,c+'15',`=MAX(0,${c}14)*'Assumptions'!$G$14`);f(m,c+'16',`=${c}7*'Assumptions'!$G$10/30`);f(m,c+'17',`=${c}8*'Assumptions'!$G$11/30`);let prev=col(3+k);f(m,c+'18',k===6?`=(${c}16-${c}17)-(${prev}7*'Assumptions'!$G$10/30-${prev}8*'Assumptions'!$G$11/30)`:`=(${c}16-${c}17)-(${prev}16-${prev}17)`);f(m,c+'19',"='Assumptions'!$G$13");f(m,c+'20',`=${c}14-${c}15+${c}13-${c}18-${c}19`);f(m,c+'21',k===6?"='Assumptions'!$G$9":`=${prev}22`);f(m,c+'22',`=SUM(${c}20:${c}21)`);}}
m.getRange('D7:O22').setNumberFormat(money);m.getRange('D12:O12').setNumberFormat('0.0%');m.freezePanes.freezeRows(6);m.freezePanes.freezeColumns(3);v(m,'C25','Jan-Jun: synthetic history. Cash schedule covers Jul-Dec only.');m.getRange('C25:K25').merge();
table(b,'C6:L9',[['Segment','Plan units','Plan price','Plan unit cost','Volume','Price','Unit cost','Fixed / opex','Total variance','Active EBITDA'],...['Core','Enterprise','Services'].map(x=>[x,null,null,null,null,null,null,null,null,null])]);for(let j=0;j<3;j++){let r=7+j,june=22+j,july=25+j;f(b,'D'+r,`=ROUND('Detail'!E${june}*1.01,0)`);f(b,'E'+r,`='Detail'!F${june}`);f(b,'F'+r,`='Detail'!G${june}`);f(b,'G'+r,`=('Detail'!E${july}-D${r})*(E${r}-F${r})`);f(b,'H'+r,`='Detail'!E${july}*('Detail'!F${july}-E${r})`);f(b,'I'+r,`=-'Detail'!E${july}*('Detail'!G${july}-F${r})`);f(b,'J'+r,`=-('Detail'!H${july}+'Detail'!I${july}-'Detail'!H${june}-'Detail'!I${june})`);f(b,'K'+r,`=SUM(G${r}:J${r})`);f(b,'L'+r,`='Detail'!L${july}`);}v(b,'C12','Reference July EBITDA');f(b,'D12',"=SUMPRODUCT(D7:D9,E7:E9)-SUMPRODUCT(D7:D9,F7:F9)-SUM('Detail'!H22:I24)");v(b,'C13','Active July EBITDA');f(b,'D13',"='Monthly'!J11");v(b,'C14','Total driver variance');f(b,'D14','=SUM(K7:K9)');b.getRange('G7:L9').setNumberFormat(money);b.getRange('D12:D14').setNumberFormat(money);v(b,'C17','Reference plan: June unit economics, July seasonality, June fixed/opex.');b.getRange('C17:L18').merge();b.getRange('C17:L18').format.wrapText=true;
table(sum,'C6:E11',[['Metric','Value','Period / basis'],['Revenue',null,'Full year'],['EBITDA',null,'Full year'],['EBITDA margin',null,'Full year'],['Ending cash',null,'December'],['Lowest cash',null,'Jul-Dec']]);f(sum,'D7',"=SUM('Monthly'!D7:O7)");f(sum,'D8',"=SUM('Monthly'!D11:O11)");f(sum,'D9','=D8/D7');f(sum,'D10',"='Monthly'!O22");f(sum,'D11',"=MIN('Monthly'!J22:O22)");sum.getRange('D7:D11').setNumberFormat(money);sum.getRange('D9').setNumberFormat('0.0%');sum.getRange('E6:E11').format.columnWidth=22;
table(sum,'C16:E28',[['Month','Revenue','EBITDA'],...Array.from({length:12},(_,i)=>[new Date(Date.UTC(2026,i,1)).toLocaleString('en-US',{month:'short',timeZone:'UTC'}),null,null])]);for(let i=0;i<12;i++){f(sum,'D'+(17+i),`='Monthly'!${col(4+i)}7`);f(sum,'E'+(17+i),`='Monthly'!${col(4+i)}11`);}sum.getRange('D17:E28').setNumberFormat(money);chart(sum,'C16:E28','Monthly revenue and EBITDA (USD)');v(sum,'H25','Review price realization, volume, and cost inflation together.');sum.getRange('H25:O26').merge();sum.getRange('H25:O26').format.wrapText=true;v(sum,'H27','Synthetic case. Cash forecast excludes debt and financing.');sum.getRange('H27:O28').merge();sum.getRange('H27:O28').format.wrapText=true;
let review=sheet(w,'Review','Simulated operating follow-up');table(review,'C6:H10',[['Measure','Frozen plan','Simulated observation','Variance','Review threshold','Decision'],['July revenue',null,872000,null,.05,null],['July EBITDA',null,-48000,null,0,null],['July ending cash',null,401000,null,250000,null],['On-time service',.95,.932,null,.95,null]]);v(review,'D7',936000);v(review,'D8',-28000);v(review,'D9',420000);for(let r=7;r<=10;r++)f(review,'F'+r,`=E${r}-D${r}`);f(review,'H7','=IF(E7<D7*(1-G7),"Reforecast","Monitor")');f(review,'H8','=IF(E8<G8,"Review margin drivers","Monitor")');f(review,'H9','=IF(E9<G9,"Escalate cash","Monitor")');f(review,'H10','=IF(E10<G10,"Review service capacity","Monitor")');review.getRange('D7:F9').setNumberFormat(money);review.getRange('D10:G10').setNumberFormat('0.0%');review.getRange('C6:H10').format.columnWidth=26;v(review,'C13','Separate synthetic monitoring exercise. Frozen plan is an illustrative management target.');review.getRange('C13:L14').merge();review.getRange('C13:L14').format.wrapText=true;
upgradeOperating(w);
actions(w,[['Validate price and cost assumptions','Finance + Sales','Day 5','July driver variance reconciled','Finance lead'],['Review low-margin contracts','Commercial + Operations','Day 10','EBITDA margin below 3%','Commercial lead'],['Reforecast and approve actions','Finance lead','Monthly close + 5 days','Volume misses plan >5%','Business unit lead'],['Monitor cash and capex','Treasury + Operations','Weekly','Cash below $250,000','Finance lead']]);terminal(w,[['July bridge',"='Variance'!D13-'Variance'!D12-'Variance'!D14"],['Cash roll-forward',"='Monthly'!O22-'Assumptions'!G56-SUM('Monthly'!J20:O20)"],['H1 revenue to raw inputs',"=SUM('Monthly'!D7:I7)-SUMPRODUCT('Source'!E7:E24,'Source'!F7:F24)"]]);
await finish(w,'Operating_Plan',{revenue:['Summary','D7'],ebitda:['Summary','D8'],margin:['Summary','D9'],endingCash:['Summary','D10'],minCash:['Summary','D11'],julyBridge:['Audit','D7'],balanceSheet:['Statements','I55'],endingDebt:['Debt','I11'],netIncomeDecember:['Statements','I23']});}

// Fleet appraisal: three mutually exclusive operating alternatives.
{
const w=Workbook.create();let s=sheet(w,'Summary','Fleet investment committee',15),a=sheet(w,'Assumptions','Fleet assumptions'),b=sheet(w,'Cash Flows','Five-year fleet cash flows');caseControl(a,['Base','Fuel shock','Low utilization']);[s,b].forEach(selected);
driver(a,8,'Discount rate',.08,.10,.08);driver(a,13,'Fuel price per gallon',4,5,4,'$0.00');driver(a,18,'Annual miles per vehicle',70000,70000,45000,num);driver(a,23,'Old annual maintenance / vehicle',22000,26000,22000,money);
table(a,'F8:H25',[['Input','Value','Units'],['Fleet size',6,'vehicles'],['Purchase cost / vehicle',130000,'USD'],['Sale of old / vehicle now',20000,'USD'],['Old terminal resale / vehicle',7000,'USD'],['New terminal resale / vehicle',42000,'USD'],['Old fuel economy',6,'mpg'],['New fuel economy',7.2,'mpg'],['New maintenance / vehicle',9000,'USD / year'],['Old downtime / vehicle',12,'days / year'],['New downtime / vehicle',4,'days / year'],['Downtime cash cost',1800,'USD / day'],['Lease / vehicle / year',33000,'USD'],['Lease upfront deposit',50000,'USD'],['Upfront capital limit',700000,'USD'],['Annual cost inflation',.03,'fraction'],['Discount years',5,'years'],['Lease deposit returned at end',50000,'USD']]);a.getRange('F8:H25').format.columnWidth=28;a.getRange('G9:G25').format.font.color='#0759e6';v(a,'C38','Synthetic USD assumptions. Pre-tax appraisal; identical service output.');a.getRange('C38:K39').merge();a.getRange('C38:K39').format.wrapText=true;
let labels={7:'Keep: maintenance',8:'Keep: fuel',9:'Keep: downtime',10:'Keep: total outflow',11:'Keep: residual receipt',12:'Keep: net cash flow',15:'Replace: maintenance',16:'Replace: fuel',17:'Replace: downtime',18:'Replace: total outflow',19:'Replace: residual receipt',20:'Replace: net cash flow',23:'Lease: rental',24:'Lease: fuel',25:'Lease: downtime',26:'Lease: total outflow',27:'Lease: returned deposit',28:'Lease: net cash flow',31:'Replace less keep: incremental CF',32:'Lease less keep: incremental CF',34:'Discount factor',35:'Keep: present value',36:'Replace: present value',37:'Lease: present value'};for(const [r,l]of Object.entries(labels))v(b,'C'+r,l);
for(let yr=0;yr<=5;yr++){let c=col(4+yr);v(b,c+'6',yr);if(!yr){[12,31,32].forEach(r=>f(b,c+r,r===12?'=0':r===31?`=${c}20-${c}12`:`=${c}28-${c}12`));f(b,c+'20',"=-'Assumptions'!G9*('Assumptions'!G10-'Assumptions'!G11)");f(b,c+'28',"='Assumptions'!G9*'Assumptions'!G11-'Assumptions'!G21");}else{
f(b,c+'7',`='Assumptions'!$G$9*'Assumptions'!$D$23*(1+'Assumptions'!$G$23)^(${c}$6-1)`);f(b,c+'8',`='Assumptions'!$G$9*'Assumptions'!$D$18/'Assumptions'!$G$14*'Assumptions'!$D$13*(1+'Assumptions'!$G$23)^(${c}$6-1)`);f(b,c+'9',`='Assumptions'!$G$9*'Assumptions'!$G$17*'Assumptions'!$G$19*(1+'Assumptions'!$G$23)^(${c}$6-1)`);f(b,c+'10',`=SUM(${c}7:${c}9)`);f(b,c+'11',yr===5?"='Assumptions'!G9*'Assumptions'!G12":'=0');f(b,c+'12',`=-${c}10+${c}11`);
f(b,c+'15',`='Assumptions'!$G$9*'Assumptions'!$G$16*(1+'Assumptions'!$G$23)^(${c}$6-1)`);f(b,c+'16',`='Assumptions'!$G$9*'Assumptions'!$D$18/'Assumptions'!$G$15*'Assumptions'!$D$13*(1+'Assumptions'!$G$23)^(${c}$6-1)`);f(b,c+'17',`='Assumptions'!$G$9*'Assumptions'!$G$18*'Assumptions'!$G$19*(1+'Assumptions'!$G$23)^(${c}$6-1)`);f(b,c+'18',`=SUM(${c}15:${c}17)`);f(b,c+'19',yr===5?"='Assumptions'!G9*'Assumptions'!G13":'=0');f(b,c+'20',`=-${c}18+${c}19`);
f(b,c+'23',`='Assumptions'!$G$9*'Assumptions'!$G$20*(1+'Assumptions'!$G$23)^(${c}$6-1)`);f(b,c+'24',`=${c}16`);f(b,c+'25',`=${c}17`);f(b,c+'26',`=SUM(${c}23:${c}25)`);f(b,c+'27',yr===5?"='Assumptions'!G25":'=0');f(b,c+'28',`=-${c}26+${c}27`);f(b,c+'31',`=${c}20-${c}12`);f(b,c+'32',`=${c}28-${c}12`);}
f(b,c+'34',`=1/(1+'Assumptions'!$D$8)^${c}$6`);for(const [r,cf]of [[35,12],[36,20],[37,28]])f(b,c+r,`=${c}${cf}*${c}34`);}
b.getRange('D7:I37').setNumberFormat(money);b.getRange('D34:I34').setNumberFormat('0.000');v(b,'C40','Year 0 sale proceeds apply only when old fleet is disposed.');b.getRange('C40:K41').merge();b.getRange('C40:K41').format.wrapText=true;
table(s,'C6:G9',[['Alternative','PV net costs','Upfront cash needed','NPV gain vs keep','Budget eligible'],['Keep',null,null,null,null],['Replace',null,null,null,null],['Lease',null,null,null,null]]);for(let i=0;i<3;i++){let r=7+i;f(s,'D'+r,`=-SUM('Cash Flows'!D${35+i}:I${35+i})`);f(s,'E'+r,`=MAX(0,-'Cash Flows'!D${[12,20,28][i]})`);f(s,'F'+r,i===0?'=0':`=$D$7-D${r}`);f(s,'G'+r,`=IF(E${r}<='Assumptions'!$G$22,"Yes","No")`);}s.getRange('D7:F9').setNumberFormat(money);s.getRange('C6:G9').format.columnWidth=24;
v(s,'C12','Lowest modeled PV cost');f(s,'D12','=INDEX(C7:C9,MATCH(MIN(D7:D9),D7:D9,0))');v(s,'C13','Recommended alternative within budget');f(s,'D13','=IF(AND(G8="Yes",D8<=D7,OR(G9="No",D8<=D9)),"Replace",IF(AND(G9="Yes",D9<D7),"Lease","Keep"))');v(s,'C15','Approval conditions');v(s,'C16','Validate quotes, residual values, availability and tax treatment.');s.getRange('C16:G18').merge();s.getRange('C16:G18').format.wrapText=true;chart(s,'C6:D9','Five-year present value of net costs (USD)','bar','I8','O23');v(s,'C22','Lease assumes maintenance included; downtime and fuel remain.');s.getRange('C22:G24').merge();s.getRange('C22:G24').format.wrapText=true;v(s,'C26','Pre-tax comparison. Depreciation and financing are excluded.');s.getRange('C26:O27').merge();
// Native two-variable sensitivity, using the actual model inputs on Assumptions.
v(a,'F29','Replacement incremental NPV sensitivity');v(a,'G30','Discount rate across / maintenance below');a.getRange('G30:K30').merge();f(a,'G32',"='Summary'!F8");a.getRange('H32:J32').values=[[.06,.08,.10]];a.getRange('G33:G35').values=[[18000],[22000],[26000]];a.dataTables.add('G32:J35',{rowInput:'D8',columnInput:'D23'});a.getRange('H32:J32').setNumberFormat('0.0%');a.getRange('G33:J35').setNumberFormat(money);a.getRange('G32').setNumberFormat(money);a.getRange('G10:G13').setNumberFormat(money);a.getRange('G16').setNumberFormat(money);a.getRange('G19:G22').setNumberFormat(money);a.getRange('G23').setNumberFormat('0.0%');a.getRange('G25').setNumberFormat(money);
let review=sheet(w,'Review','Simulated fleet benefits review');table(review,'C6:H10',[['Measure','Plan','Simulated observation','Variance','Units','Review action'],['Annual maintenance',54000,58000,null,'USD','Review warranty and repair mix'],['Fuel economy',7.2,6.9,null,'mpg','Review duty cycle and driver factors'],['Annual fleet downtime',24,30,null,'days','Investigate service availability'],['Net upfront cash',660000,672000,null,'USD','Reconcile purchase and disposal invoices']]);for(let r=7;r<=10;r++)f(review,'F'+r,`=E${r}-D${r}`);review.getRange('C6:H10').format.columnWidth=26;review.getRange('D7:F7').setNumberFormat(money);review.getRange('D8:F8').setNumberFormat('0.0');review.getRange('D10:F10').setNumberFormat(money);v(review,'C13','Simulated review only. Annualized observations are not realized employer savings.');review.getRange('C13:L14').merge();review.getRange('C13:L14').format.wrapText=true;
upgradeFleet(w);
actions(w,[['Obtain purchase and lease quotes','Fleet + Procurement','Day 10','Comparable service and coverage','Procurement lead'],['Approve capital and liquidity','Finance + Treasury','Day 15','Net upfront cash within $700k','Investment committee'],['Verify tax and residual assumptions','Finance','Before commitment','Tax-adjusted economics reviewed','Finance lead'],['Review benefits after commissioning','Fleet + Finance','Days 30 / 90 / 180','Maintenance, mpg, downtime vs plan','Operations lead']]);terminal(w,[['Replace incremental NPV',"='Summary'!F8-SUMPRODUCT('After Tax'!D34:I34,'After Tax'!D28:I28)"],['Lease incremental NPV',"='Summary'!F9-SUMPRODUCT('After Tax'!D35:I35,'After Tax'!D28:I28)"],['Loan repaid in year 5',"='Financing'!I10"]]);await finish(w,'Fleet_Investment',{keepPV:['Summary','D7'],replacePV:['Summary','D8'],leasePV:['Summary','D9'],replaceNPV:['Summary','F8'],upfront:['Summary','E8'],recommendation:['Summary','D13']});}

// Liquidity: invoice-level timing, boundary carry-forward and explicit financing gaps.
{
const w=Workbook.create();let s=sheet(w,'Summary','13-week liquidity and working capital',15),a=sheet(w,'Assumptions','Cash timing assumptions'),b=sheet(w,'Weekly','Weekly cash forecast',16),iv=sheet(w,'Invoices','Synthetic open receivables',10),r=sheet(w,'Review','Simulated four-week forecast review');caseControl(a,['Base','Delayed receipts','Mitigation']);[s,b,iv,r].forEach(selected);driver(a,8,'Receipt delay (weeks)',0,2,2,'0');driver(a,13,'Eligible acceleration (weeks)',0,0,2,'0');driver(a,18,'Capex week',6,6,14,'0');
table(a,'F8:H16',[['Input','Value','Basis'],['Opening cash',180000,'Synthetic opening bank balance'],['Minimum cash',100000,'Management floor'],['Weekly direct cash sales',20000,'Excludes open invoice receipts'],['Weekly payroll',45000,'Cash payments'],['Weekly fuel',20000,'Cash payments'],['Weekly supplier AP',35000,'Cash payments'],['Weekly lease payments',12000,'Cash payments'],['One-time capex',90000,'Deferred to week 14 in action case']]);a.getRange('F8:H16').format.columnWidth=28;a.getRange('G9:G16').format.font.color='#0759e6';v(a,'C25','Week 1 starts 5-Oct-2026. No financing availability is assumed.');a.getRange('C25:K26').merge();a.getRange('C25:K26').format.wrapText=true;v(a,'C28','Action changes timing only. Deferred capex remains a week-14 obligation.');a.getRange('C28:K29').merge();a.getRange('C28:K29').format.wrapText=true;
let invoices=Array.from({length:26},(_,i)=>{let week=Math.floor(i/2)+1;return ['INV-'+(1001+i),'Synthetic account '+(i%5+1),week,44000+(i%4)*3000,week===4||week===5?1:0,null,null,null];});table(iv,'C6:J32',[['Invoice ID','Account','Base week','USD amount','Eligible acceleration','Active week','Receipt date','At-risk aging'],...invoices]);for(let i=0;i<26;i++){let row=7+i;f(iv,'H'+row,`=MAX(1,E${row}+'Assumptions'!$D$8-G${row}*'Assumptions'!$D$13)`);f(iv,'I'+row,`=DATE(2026,10,5)+7*(H${row}-1)`);v(iv,'J'+row,i>=6&&i<=9?'Overdue at opening':'Current at opening');}iv.getRange('F7:F32').setNumberFormat(money);iv.getRange('I7:I32').setNumberFormat('mm/dd/yy');iv.getRange('C6:J32').format.columnWidth=23;table(iv,'K6:L6',[['Original due date','Days past due at 5-Oct']]);for(let i=0;i<26;i++){let rr=7+i,wk=Math.floor(i/2)+1;v(iv,'K'+rr,new Date(Date.UTC(2026,9,wk===4?(-9):wk===5?(-2):5+7*(wk-1))));f(iv,'L'+rr,`=MAX(0,DATE(2026,10,5)-K${rr})`);}iv.getRange('K7:K32').setNumberFormat('mm/dd/yy');iv.getRange('L7:L32').setNumberFormat('0');iv.getRange('K6:L32').format.columnWidth=24;v(iv,'C35','All 26 invoices are open at forecast start. Eligible invoices need collection consent.');iv.getRange('C35:K36').merge();iv.getRange('C35:K36').format.wrapText=true;
let names=['Opening cash','Open invoice collections','Direct cash sales','Total receipts','Payroll','Fuel','Supplier payments','Lease payments','Capex','Total payments','Net cash flow','Ending cash before financing','Minimum cash','Cumulative funding shortfall'];names.forEach((x,i)=>v(b,'C'+(7+i),x));for(let i=0;i<13;i++){let c=col(4+i),prev=col(3+i),wk=i+1;v(b,c+'5',wk);v(b,c+'6',new Date(Date.UTC(2026,9,5+7*i)));b.getRange(c+'6').setNumberFormat('d-mmm');f(b,c+'7',i===0?"='Assumptions'!G9":`=${prev}18`);f(b,c+'8',`=SUMIFS('Invoices'!$F$7:$F$32,'Invoices'!$H$7:$H$32,${c}$5)`);f(b,c+'9',"='Assumptions'!$G$11");f(b,c+'10',`=SUM(${c}8:${c}9)`);for(let j=0;j<4;j++)f(b,c+(11+j),`='Assumptions'!$G$${12+j}`);f(b,c+'15',`=IF(${c}$5='Assumptions'!$D$18,'Assumptions'!$G$16,0)`);f(b,c+'16',`=SUM(${c}11:${c}15)`);f(b,c+'17',`=${c}10-${c}16`);f(b,c+'18',`=SUM(${c}7,${c}17)`);f(b,c+'19',"='Assumptions'!$G$10");f(b,c+'20',`=MAX(0,${c}19-${c}18)`);}b.getRange('D7:P20').setNumberFormat(money);b.getRange('D18:P18').conditionalFormats.addCustom('D18<D19',{fill:'#fee2e2',font:{color:'#b91c1c',bold:true}});b.freezePanes.freezeRows(6);b.freezePanes.freezeColumns(3);v(b,'C23','Funding shortfall is a requirement, not an assumed available credit line.');b.getRange('C23:L24').merge();b.getRange('C23:L24').format.wrapText=true;
table(s,'C6:E12',[['Metric','Value','Basis'],['Lowest weekly cash',null,'Before financing'],['Funding needed to maintain floor',null,'Peak cumulative gap'],['Ending cash',null,'Week 13'],['Open invoices beyond horizon',null,'Carry-forward, not lost'],['Capex beyond horizon',null,'Future obligation'],['Opening overdue receivables',null,'Eligible collection queue']]);f(s,'D7',"=MIN('Weekly'!D18:P18)");f(s,'D8',"=MAX('Weekly'!D20:P20)");f(s,'D9',"='Weekly'!P18");f(s,'D10',"=SUMIFS('Invoices'!F7:F32,'Invoices'!H7:H32,\">13\")");f(s,'D11',"=IF('Assumptions'!D18>13,'Assumptions'!G16,0)");f(s,'D12',"=SUMIFS('Invoices'!F7:F32,'Invoices'!G7:G32,1)");s.getRange('D7:D12').setNumberFormat(money);s.getRange('E6:E12').format.columnWidth=26;
table(s,'C16:E29',[['Week','Ending cash','Minimum floor'],...Array.from({length:13},(_,i)=>['W'+(i+1),null,null])]);for(let i=0;i<13;i++){f(s,'D'+(17+i),`='Weekly'!${col(4+i)}18`);f(s,'E'+(17+i),`='Weekly'!${col(4+i)}19`);}s.getRange('D17:E29').setNumberFormat(money);let cashChart=chart(s,'C16:E29','Weekly cash before financing (USD)','line','H8','O23');cashChart.yAxis={numberFormatCode:'$0,"k"',numberFormatSourceLinked:false,textStyle:{typeface:'Arial',fontSize:11}};v(s,'H25','Accelerate eligible collections with consent. Defer capex only after review.');s.getRange('H25:O27').merge();s.getRange('H25:O27').format.wrapText=true;
table(r,'C6:J10',[['Week','Baseline receipts','Simulated receipts','Receipt variance','Baseline payments','Simulated payments','Payment variance','Net cash variance'],...[1,2,3,4].map(x=>[x,null,null,null,null,null,null,null])]);let baseReceipts=[111000,123000,111000,123000],pay=[112000,112000,112000,112000];for(let i=0;i<4;i++){let row=7+i;v(r,'D'+row,baseReceipts[i]);v(r,'E'+row,[101000,128000,111000,118000][i]);f(r,'F'+row,`=E${row}-D${row}`);v(r,'G'+row,pay[i]);v(r,'H'+row,[114000,111000,112000,113000][i]);f(r,'I'+row,`=H${row}-G${row}`);f(r,'J'+row,`=F${row}-I${row}`);}r.getRange('D7:J10').setNumberFormat(money);v(r,'C13','Frozen baseline, simulated observations. Review is not tied to active case.');r.getRange('C13:L14').merge();r.getRange('C13:L14').format.wrapText=true;v(r,'C17','Net cash variance');f(r,'D17','=SUM(J7:J10)');v(r,'C18','Absolute receipt error / baseline receipts');f(r,'D18','=(ABS(F7)+ABS(F8)+ABS(F9)+ABS(F10))/SUM(D7:D10)');r.getRange('D18').setNumberFormat('0.0%');
upgradeCash(w);
actions(w,[['Verify bank and invoice opening balances','Treasury + AR','Day 1','Opening bank / AR reconciled','Treasury lead'],['Collect eligible overdue invoices','AR + Account lead','Week 2','Customer consent and cash receipt','Credit lead'],['Review capex timing','Operations + Finance','Before week 6','Operational impact of deferral','Finance lead'],['Arrange liquidity contingency','Treasury','Before floor breach','Confirmed facility and covenants','Treasury lead'],['Refresh receipts / payments','Treasury + AP','Every Monday','Prior week actuals reconciled','Finance lead']]);terminal(w,[['Invoices collected plus carried forward',"=SUM('Invoices'!F7:F32,'New Invoices'!E7:E32)-SUM('Weekly'!D8:AC8,'Weekly'!D10:AC10)-'Summary'!D10"],['Cash roll-forward',"='Weekly'!AC27-'Assumptions'!G9-SUM('Weekly'!D18:AC18,'Weekly'!D24:AC24)+SUM('Weekly'!D20:AC21,'Weekly'!D25:AC25)"],['Capex paid plus future obligation',"='Assumptions'!G16-SUM('Weekly'!D16:AC16)-'Summary'!D11"],['Simulated review bridge',"=SUM('Review'!J7:J10)-SUM('Review'!F7:F10)+SUM('Review'!I7:I10)"]]);await finish(w,'Cash_Working_Capital',{minCash:['Summary','D7'],fundingGap:['Summary','D8'],endingCash:['Summary','D9'],futureReceipts:['Summary','D10'],deferredCapex:['Summary','D11'],overdue:['Summary','D12'],residualGap:['Summary','D13'],unfundedMinimum:['Summary','D14'],endingDebt:['Weekly','AC26'],fundingCosts:['Weekly','AC31']});}
await fs.writeFile(out+'/scenario_captures.json',JSON.stringify(captures,null,2));await fs.writeFile(out+'/authoring_audit.json',JSON.stringify(evidence,null,2));
