import fs from 'node:fs/promises';
import {Workbook,SpreadsheetFile,FileBlob} from '@oai/artifact-tool';
const p=(process.env.QUINCY_FINANCE_DIR || process.cwd())+'/';let results=[];
function assert(x,msg){if(!x)throw Error(msg);results.push(msg)}
for(const [name,sheet,cell,input,changed] of [['Operating_Plan','Summary','D8','D24',.08],['Fleet_Investment','Summary','D8','G10',150000],['Cash_Working_Capital','Summary','D7','G9',210000]]){
 let w=await SpreadsheetFile.importXlsx(await FileBlob.load(p+name+'.xlsx'));w.recalculate();let a=w.worksheets.getItem('Assumptions'),s=w.worksheets.getItem(sheet);let initial=s.getRange(cell).values[0][0];let actuals=name==='Operating_Plan'?JSON.stringify(w.worksheets.getItem('Source').getRange('C7:I24').values):null;
 a.getRange('D5').values=[[2]];w.recalculate();assert(s.getRange(cell).values[0][0]!==initial,name+': selector changes result');a.getRange('D5').values=[[1]];a.getRange(input).values=[[changed]];w.recalculate();assert(s.getRange(cell).values[0][0]!==initial,name+': edited input changes result');if(actuals)assert(actuals===JSON.stringify(w.worksheets.getItem('Source').getRange('C7:I24').values),name+': history preserved');
 if(name==='Operating_Plan'){a.getRange('D10').values=[[null]];a.getRange('D5').values=[[1]];w.recalculate();assert(typeof s.getRange(cell).values[0][0]==='number','Operating: missing inactive driver does not block base');a.getRange('D5').values=[[2]];w.recalculate();assert(typeof s.getRange(cell).values[0][0]!=='number','Operating: selected missing driver exposes unavailable result');}
 if(name==='Fleet_Investment'){a.getRange('G10').values=[[130000]];a.getRange('G22').values=[[100000]];w.recalculate();assert(s.getRange('D13').values[0][0]!=='Replace','Fleet: capital limit changes recommendation');let sens=a.getRange('I34').values[0][0];a.getRange('D8').values=[[.08]];a.getRange('D23').values=[[22000]];w.recalculate();assert(Math.abs(s.getRange('F8').values[0][0]-sens)<.01,'Fleet: native sensitivity base equals build');for(let rr=33;rr<=35;rr++)for(let cc=8;cc<=10;cc++){let addr=String.fromCharCode(64+cc)+rr;let expected=a.getRange(addr).values[0][0];a.getRange('D8').values=[[a.getRange(String.fromCharCode(64+cc)+'32').values[0][0]]];a.getRange('D23').values=[[a.getRange('G'+rr).values[0][0]]];w.recalculate();assert(Math.abs(s.getRange('F8').values[0][0]-expected)<.01,'Fleet: sensitivity '+addr+' equals independently selected build');}}
 if(name==='Cash_Working_Capital'){a.getRange('G9').values=[[0]];w.recalculate();assert(s.getRange(cell).values[0][0]<0,'Cash: zero opening cash remains valid zero');let ids=w.worksheets.getItem('Invoices').getRange('C7:C32').values.flat();assert(new Set(ids).size===26,'Cash: unique invoice keys');}
}
await fs.writeFile(p+'recalculation_tests.json',JSON.stringify(results,null,2));console.log(results);
